@extends('layouts.app')
@section('title',$method->name.' · Payments')
@section('content')
@php($currency=$settings['currency_symbol']??'Rs.')
<div class="page-heading"><div><span class="eyebrow">PAYMENT METHOD</span><h1>{{ $method->name }}</h1><p>Review bills, collections and charges for this payment method.</p></div><div class="heading-actions"><a class="btn secondary" href="{{ route('manage.index',['resource'=>'payment-methods']+array_intersect_key($filters,array_flip(['range','from','to']))) }}"><x-icon name="arrow-left"/>All payment methods</a>@can('payment-methods.edit')<a class="btn primary" href="{{ route('manage.edit',['payment-methods',$method->id]) }}"><x-icon name="pencil"/>Edit payment method</a>@endcan</div></div>
<x-sales-visibility-note/>
@include('payment-methods.partials.filters')
@include('payment-methods.partials.totals')
<section class="card payment-activity-card"><div class="card-heading"><div><h2>Bills & payment history</h2><p class="muted">{{ $activity->total() }} entries · {{ $totals['bills'] }} bills involved in this period</p></div><span class="badge {{ $method->active?'green':'slate' }}">{{ $method->active?'Active':'Inactive' }}</span></div>
<div class="payment-history-note">Includes checkout payments, due collections, account payments and refunds. Voided bills are excluded. Charges use the amounts saved on each bill.</div>
<div class="table-wrap"><table class="payment-activity-table"><thead><tr><th>Bill / date</th><th>Customer / cashier</th><th>Activity</th><th>Received / change</th><th>Collected</th><th>Charges</th><th>Refund</th></tr></thead><tbody>
@forelse($activity as $entry)
<tr><td>@if($entry->sale_id)@can('sales.view')<a class="text-link" href="{{ route('sales.show',$entry->sale_id) }}">{{ $entry->bill }} <x-icon name="arrow-up-right" :size="14"/></a>@else<strong>{{ $entry->bill }}</strong>@endcan @else<strong>Account payment #{{ $entry->entry_id }}</strong><small class="table-secondary">Opening balance / unallocated credit</small>@endif<small class="table-secondary">{{ \Carbon\Carbon::parse($entry->occurred_at)->format('d M Y, h:i A') }}</small></td><td><strong>{{ $entry->customer }}</strong><small class="table-secondary">{{ $entry->cashier }}</small></td><td><span class="badge {{ $entry->kind==='Refund'?'amber':($entry->kind==='Checkout'?'slate':'green') }}">{{ $entry->kind }}</span>@if($entry->reference)<small class="table-secondary payment-reference">{{ $entry->reference }}</small>@endif</td><td class="payment-number">{{ $currency }} {{ \App\Support\Money::display($entry->received) }}@if(\App\Support\Money::compare((string)$entry->change_amount,0)>0)<small class="table-secondary">Change {{ $currency }} {{ \App\Support\Money::display($entry->change_amount) }}</small>@endif</td><td class="payment-number"><strong>{{ $currency }} {{ \App\Support\Money::display($entry->collected) }}</strong></td><td class="payment-number">@if(\App\Support\Money::compare((string)$entry->charges,0)>0)<strong>{{ $currency }} {{ \App\Support\Money::display($entry->charges) }}</strong><small class="table-secondary">{{ \App\Support\Money::compare((string)$entry->customer_charges,0)>0?'Customer paid':'Business paid' }}</small>@else<span class="muted">—</span>@endif</td><td class="payment-number">{{ \App\Support\Money::compare((string)$entry->refunded,0)>0?$currency.' '.\App\Support\Money::display($entry->refunded):'—' }}</td></tr>
@empty
<tr><td colspan="7"><div class="empty-state"><x-icon name="receipt-text" :size="34"/><h3>No payment activity in this period</h3><p>Choose another quick range or enter custom dates to find earlier bills.</p></div></td></tr>
@endforelse
</tbody></table></div><div class="pagination">{{ $activity->links() }}</div></section>
<details class="card payment-method-settings"><summary><span><x-icon name="settings-2"/>Payment method settings</span><x-icon name="chevron-down" :size="16"/></summary><dl class="detail-grid"><div><dt>Code / type</dt><dd>{{ $method->code }} · {{ str_replace('_',' ',ucfirst(strtolower($method->type))) }}</dd></div><div><dt>Current charge</dt><dd>@if($method->has_charge){{ $method->charge_type==='PERCENTAGE'?rtrim(rtrim($method->charge_value,'0'),'.').'%':$currency.' '.\App\Support\Money::display($method->charge_value) }} · {{ ucfirst(strtolower($method->charge_bearer)) }} paid<small class="table-secondary">Applies from {{ $currency }} {{ \App\Support\Money::display($method->charge_minimum_amount) }}</small>@else No charge @endif</dd></div></dl></details>
@endsection
