@extends('layouts.app')
@section('title','Point of sale')
@section('main-class','pos-main')
@section('content')
<div class="pos-heading"><div><span class="eyebrow">SELLING MADE SIMPLE</span><h1>Point of sale</h1></div><span class="badge {{ $register?'green':'amber' }}">{{ $register?'REG-'.$register->id.' · Ready to sell':'Open a register to sell' }}</span></div>
@if(!$register)<div class="notice info"><x-icon name="wallet"/><span>Start your shift by opening a register.</span>@can('register.open')<a class="btn primary" href="{{ route('register.index') }}">Open register</a>@endcan</div>@endif
<div id="pos" data-products-url="{{ route('pos.products') }}" data-quote-url="{{ route('pos.quote') }}" data-complete-url="{{ route('pos.complete') }}" data-currency="{{ $settings['currency_symbol']??'Rs.' }}" data-quantity-precision="{{ $settings['quantity_decimals']??3 }}" data-decimals="{{ $settings['number_decimals']??2 }}" data-barcode="{{ ($settings['barcode_enabled']??true)?1:0 }}" data-default-method="{{ $settings['default_payment_method']??'' }}" data-register="{{ $register?1:0 }}">
<div class="pos-grid"><section class="pos-catalog"><div class="catalog-tools"><label class="search-field"><x-icon name="search"/><input id="product-search" type="search" maxlength="255" placeholder="{{ ($settings['barcode_enabled']??true)?'Scan barcode or search products…':'Search products…' }}" autocomplete="off" aria-label="Find products" autofocus><kbd>↵</kbd></label><select id="product-category" aria-label="Product category"><option value="">All categories</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></div><div class="catalog-status"><span id="product-count">Loading products…</span><span>Click a product to add it</span></div><div id="product-results" class="product-grid" aria-live="polite"></div></section>
<aside class="card cart-panel"><div class="card-heading"><h2>Current order <span id="cart-count" class="badge slate">0</span></h2><button class="text-link text-danger" id="clear-cart" type="button">Clear</button></div><div id="cart-items" class="cart-items"></div><div class="cart-bottom"><label class="field compact">Customer<select id="customer"><option value="">Walk-in customer</option>@foreach($customers as $c)<option value="{{ $c->id }}" @selected(($settings['default_customer']??null)==$c->id)>{{ $c->name }}</option>@endforeach</select></label>@if($settings['allow_discount']??true)<div class="discount-row"><label for="discount">Discount ({{ $settings['currency_symbol']??'Rs.' }})</label><input id="discount" type="number" min="0" step="0.01" value="0"></div>@else<input id="discount" type="hidden" value="0">@endif<div class="order-summary"><span>Subtotal</span><strong id="cart-subtotal">0.00</strong></div><div class="order-summary total"><span>Order total</span><strong id="cart-total">0.00</strong></div><p class="muted text-xs">Payment charges appear when you select a payment method.</p><button id="open-payment" class="btn primary checkout-button" type="button" @disabled(!$register)><x-icon name="credit-card"/>Payment <x-icon name="arrow-right"/></button><div id="pos-message" role="status" class="pos-message"></div></div></aside></div>
<dialog id="payment-dialog" class="payment-dialog"><div class="modal-heading"><div><span class="eyebrow">CHECKOUT</span><h2>Payment</h2></div><button class="icon-button" id="close-payment" type="button" aria-label="Close payment"><x-icon name="x"/></button></div><div class="modal-body"><div class="payment-order"><span>Order total</span><strong id="payment-base">0.00</strong></div><label class="field-label">Select payment method</label><div class="payment-options">@foreach($methods as $method)<button type="button" class="payment-option" data-method-id="{{ $method->id }}" data-method-type="{{ $method->type }}"><x-icon :name="match($method->type){'CASH'=>'banknote','CARD'=>'credit-card','QR'=>'qr-code',default=>'landmark'}"/><span>{{ $method->name }}</span></button>@endforeach</div>@if($methods->isEmpty())<div class="notice error">No active payment methods. Ask an administrator to enable one.</div>@endif
<div id="charge-detail" class="charge-detail" hidden></div><div class="payment-total"><span id="payable-label">Amount to pay</span><strong id="payment-payable">—</strong></div><div id="cash-fields"><label class="field">Cash received<input id="cash-received" inputmode="decimal" type="number" min="0" step="0.01"></label><div id="quick-cash" class="quick-cash"></div><div class="change-row"><span>Change</span><strong id="cash-change">0.00</strong></div></div><label class="field" id="reference-field">Payment reference (optional)<input id="payment-reference" maxlength="255"></label><div id="payment-error" class="notice error" role="alert" hidden></div><button type="button" id="confirm-payment" class="btn primary w-full" disabled><x-icon name="check"/>Complete sale</button><p class="payment-note">Totals are verified by the server before the sale is saved.</p></div></dialog>
<dialog id="receipt-dialog" class="receipt-dialog"><div class="modal-heading"><div><span class="eyebrow">SALE COMPLETE</span><h2 id="receipt-invoice">Receipt</h2></div><button class="icon-button" id="close-receipt" type="button" aria-label="Close receipt"><x-icon name="x"/></button></div><iframe id="receipt-frame" title="Sale receipt"></iframe><div class="receipt-actions"><a id="receipt-external" class="btn secondary" target="_blank">Open receipt</a><button class="btn secondary" id="print-receipt" type="button" disabled><x-icon name="printer"/>Print</button><button class="btn primary" id="next-sale" type="button">Next sale</button></div></dialog>
</div>
@endsection
@push('scripts')@vite('resources/js/pos.js')@endpush
