@extends('layouts.app')
@section('title','Purchase '.$purchase->reference)
@section('content')
@can('purchase_returns.create')@if($purchase->status==='ACTIVE')<a class="btn secondary mb-6" href="{{ route('returns.create',['purchase','original_id'=>$purchase->id]) }}">Purchase Return</a>@endif @endcan
@php($currency=$settings['currency_symbol']??'Rs.')
@php($paymentStatus=$purchase->payment_status)
<div class="page-heading purchase-page-heading"><div><span class="eyebrow">PURCHASE DETAILS</span><h1>{{ $purchase->reference }} <span class="badge {{ $paymentStatus==='Paid'?'green':($paymentStatus==='Voided'?'red':'amber') }}">{{ $paymentStatus }}</span></h1><p>{{ $purchase->purchase_date->format($settings['date_format']??'d/m/Y') }} · {{ $purchase->user->name }}</p></div><div class="heading-actions"><a class="btn secondary" href="{{ route('purchases.index') }}"><x-icon name="arrow-left"/>Purchases</a><button type="button" class="btn secondary" onclick="window.print()"><x-icon name="printer"/>Print</button>@if($purchase->status==='ACTIVE')@can('purchases.edit')<a class="btn secondary" href="{{ route('purchases.edit',$purchase) }}"><x-icon name="pencil"/>Edit purchase</a>@endcan @endif</div></div>
<div class="purchase-status-stats"><div class="card"><span>Purchase total</span><strong>{{ $currency }} {{ \App\Support\Money::display($purchase->total) }}</strong><small>{{ $purchase->items->count() }} received items</small></div><div class="card"><span>Paid to supplier</span><strong>{{ $purchase->payment_tracking?$currency.' '.\App\Support\Money::display($purchase->paid_amount):'Unrecorded' }}</strong><small>After recorded refunds</small></div><div class="card purchase-due-stat {{ $paymentStatus==='Paid'?'is-settled':'' }}"><span>Balance due</span><strong>{{ $purchase->due_amount!==null?$currency.' '.\App\Support\Money::display($purchase->due_amount):'Unrecorded' }}</strong><small>{{ $paymentStatus==='Paid'?'Payment settled':'Supplier balance' }}</small></div><div class="card"><span>Payment status</span><strong>{{ $paymentStatus }}</strong><small>{{ $purchase->status==='ACTIVE'?'Active delivery':'Delivery reversed' }}</small></div></div>
<div class="purchase-detail-grid"><div class="purchase-detail-main">
<section class="card"><div class="purchase-section-heading"><span class="customer-section-icon"><x-icon name="package-plus"/></span><div><h2>Received products</h2><p>Recorded quantity, cost and selling price for this delivery.</p></div></div><div class="table-wrap"><table><thead><tr><th>Product</th><th class="text-right">Quantity</th><th class="text-right">Cost / unit</th><th class="text-right">Sell / unit</th><th class="text-right">Amount</th></tr></thead><tbody>@foreach($purchase->items as $item)<tr><td>@can('products.view')<a class="text-link" href="{{ route('manage.show',['products',$item->product_id]) }}">{{ $item->name }}</a>@else<strong>{{ $item->name }}</strong>@endcan @if(\App\Support\Money::compare($item->allocated_charge,0)>0)<small class="cell-note">Allocated cost: +{{ $currency }} {{ \App\Support\Money::display($item->allocated_charge) }} · landed cost / primary unit {{ \App\Support\Money::display($item->base_cost) }}</small>@endif</td><td class="text-right">{{ (float)$item->quantity }} {{ $item->unit }}</td><td class="text-right">{{ \App\Support\Money::display($item->cost) }}</td><td class="text-right">{{ $item->selling_price!==null?\App\Support\Money::display($item->selling_price):'—' }}</td><td class="text-right font-semibold">{{ \App\Support\Money::display($item->total) }}</td></tr>@endforeach</tbody></table></div><div class="form-footer"><span class="muted">{{ $purchase->notes }}</span><strong>Total {{ $currency }} {{ \App\Support\Money::display($purchase->total) }}</strong></div></section>
@if($purchase->charges->isNotEmpty())<section class="card"><div class="purchase-section-heading"><span class="customer-section-icon"><x-icon name="truck"/></span><div><h2>Shipping & other charges</h2><p>{{ $purchase->charge_treatment==='COST'?'Included in the cost of received products.':'Recorded as expenses.' }}</p></div></div><div class="purchase-payment-fields"><dl class="purchase-charge-list">@foreach($purchase->charges as $charge)<div><dt>{{ $charge->label }} @if($charge->expense_id)@can('expenses.view')<a class="text-link" href="{{ route('manage.show',['expenses',$charge->expense_id]) }}">Expense #{{ $charge->expense_id }}</a>@endcan @endif</dt><dd>{{ $currency }} {{ \App\Support\Money::display($charge->amount) }}</dd></div>@endforeach<div><dt>Products subtotal</dt><dd>{{ $currency }} {{ \App\Support\Money::display($purchase->subtotal??$purchase->total) }}</dd></div><div><dt>Extra charges</dt><dd>{{ $currency }} {{ \App\Support\Money::display($purchase->charges_total) }}</dd></div></dl></div></section>@endif
<section class="card" id="purchase-payments"><div class="purchase-section-heading"><span class="customer-section-icon"><x-icon name="wallet"/></span><div><h2>Payment history</h2><p>Every supplier payment, refund and previous balance.</p></div><span class="badge slate">{{ $purchase->payments->count() }} entries</span></div><div class="table-wrap"><table><thead><tr><th>Payment</th><th>Method / reference</th><th>Recorded by</th><th class="text-right">Amount</th></tr></thead><tbody>@forelse($purchase->payments->sortByDesc('id') as $payment)<tr><td><strong>{{ match($payment->kind){'REFUND'=>'Supplier refund','OPENING'=>'Previous payment balance',default=>'Supplier payment'} }}</strong><small class="cell-note">{{ $payment->paid_at->format(($settings['date_format']??'d/m/Y').' h:i A') }}</small></td><td>{{ $payment->method_name }}<small class="cell-note">{{ $payment->reference??($payment->register_id?'REG-'.$payment->register_id:'—') }}</small>@if($payment->notes)<small class="cell-note">{{ $payment->notes }}</small>@endif</td><td>{{ $payment->user->name }}</td><td class="text-right font-semibold {{ $payment->kind==='REFUND'?'text-danger':'' }}">{{ $payment->kind==='REFUND'?'−':'' }}{{ $currency }} {{ \App\Support\Money::display($payment->amount) }}@if(\App\Support\Money::compare($payment->change,0)>0)<small class="cell-note">Given {{ \App\Support\Money::display($payment->amount_paid) }} · change {{ \App\Support\Money::display($payment->change) }}</small>@endif</td></tr>@empty<tr><td colspan="4" class="empty-cell">{{ $purchase->payment_tracking?'No payments yet. Use Pay due when you pay the supplier.':'Previous payments were not tracked. Set the previous balance to begin.' }}</td></tr>@endforelse</tbody></table></div></section>
</div><aside class="card purchase-details-summary"><div class="purchase-supplier-profile"><span class="eyebrow">SUPPLIER</span><strong>{{ $purchase->supplier->name }}</strong>@if($purchase->supplier->phone)<p>{{ $purchase->supplier->phone }}</p>@endif @if($purchase->supplier->email)<p>{{ $purchase->supplier->email }}</p>@endif @can('suppliers.view')<a class="text-link" href="{{ route('manage.show',['suppliers',$purchase->supplier_id]) }}">View supplier<x-icon name="arrow-up-right" :size="14"/></a>@endcan</div><h2>Manage this bill</h2>
@if($purchase->status==='ACTIVE')
@if(!$purchase->payment_tracking)<p class="muted">Set how much was paid before payment tracking started. This only records the balance.</p>@can('purchases.set_balance')<button type="button" class="btn primary w-full" data-purchase-dialog="purchase-balance-dialog"><x-icon name="wallet"/>Set previous balance</button>@endcan
@elseif(\App\Support\Money::compare($purchase->due_amount,0)>0)<p class="muted">{{ $currency }} {{ \App\Support\Money::display($purchase->due_amount) }} remains due to this supplier.</p>@can('purchases.pay')<button type="button" class="btn primary w-full" data-purchase-dialog="purchase-pay-dialog"><x-icon name="credit-card"/>Pay due</button>@endcan
@else<p class="conversion-note"><x-icon name="circle-check" :size="18"/>This purchase is fully paid.</p>@endif
@can('purchases.refund')@if(\App\Support\Money::compare($purchase->paid_amount,0)>0)<button type="button" class="btn secondary w-full mt-4" data-purchase-dialog="purchase-refund-dialog"><x-icon name="arrow-left"/>Record supplier refund</button>@endif @endcan @canany(['purchases.void','purchases.delete'])<button type="button" class="text-link text-danger mt-6" data-purchase-dialog="purchase-void-dialog"><x-icon name="ban" :size="15"/>Void purchase</button>@endcanany
@else<p class="muted">This delivery was voided. Stock and payment history remain available.</p>@endif
</aside></div>
@if($purchase->status==='ACTIVE')
@can('purchases.pay')
@if($purchase->payment_tracking && \App\Support\Money::compare($purchase->due_amount,0)>0)
@include('purchases.partials.payment-dialog',['dialogId'=>'purchase-pay-dialog','action'=>route('purchases.payments.store',$purchase),'heading'=>'Pay supplier due','limit'=>$purchase->due_amount,'paymentAction'=>'PAYMENT','buttonLabel'=>'Record payment','note'=>'Enter the amount you paid. Partial payments keep the remaining balance due.'])
@endif
@endcan
@can('purchases.set_balance')
@if(!$purchase->payment_tracking)<dialog id="purchase-balance-dialog" class="purchase-payment-dialog"><div class="modal-heading"><div><span class="eyebrow">PREVIOUS PAYMENTS</span><h2>Set previous balance</h2></div><button type="button" class="icon-button" data-close-purchase-dialog aria-label="Close balance dialog"><x-icon name="x"/></button></div><form class="modal-body" method="POST" action="{{ route('purchases.balance',$purchase) }}">@csrf<input type="hidden" name="payment_action" value="BALANCE"><input type="hidden" name="confirmed" value="1"><div class="purchase-dialog-balance"><span>Purchase total</span><strong>{{ $currency }} {{ \App\Support\Money::display($purchase->total) }}</strong></div><p class="muted">Enter payments already made before tracking started. This records the previous balance without moving cash from your register.</p><label class="field">Previously paid<input type="number" name="previously_paid" value="{{ old('previously_paid',0) }}" min="0" max="{{ $purchase->total }}" step="0.01" required inputmode="decimal"></label><div class="form-footer"><button type="button" class="btn secondary" data-close-purchase-dialog>Cancel</button><button class="btn primary">Save previous balance</button></div></form></dialog>@endif
@endcan
@can('purchases.refund')
@if(\App\Support\Money::compare($purchase->paid_amount,0)>0)
@include('purchases.partials.payment-dialog',['dialogId'=>'purchase-refund-dialog','action'=>route('purchases.refunds.store',$purchase),'heading'=>'Record supplier refund','limit'=>$purchase->paid_amount,'paymentAction'=>'REFUND','buttonLabel'=>'Record refund','note'=>'Record money received back from the supplier. Cash refunds are added to your open register.'])
@endif
@endcan
@canany(['purchases.void','purchases.delete'])
<dialog id="purchase-void-dialog" class="purchase-payment-dialog"><div class="modal-heading"><div><span class="eyebrow">REVERSE DELIVERY</span><h2>Void purchase</h2></div><button type="button" class="icon-button" data-close-purchase-dialog aria-label="Close void dialog"><x-icon name="x"/></button></div><div class="modal-body">@if(\App\Support\Money::compare($purchase->paid_amount,0)>0)<p class="muted">Record the supplier refund before voiding this paid purchase.</p><button type="button" class="btn secondary" data-close-purchase-dialog>Close</button>@else<form method="POST" action="{{ route(auth()->user()->hasPermission('purchases.void')?'purchases.void':'purchases.destroy',$purchase) }}" data-confirm="Void this purchase and reverse its unused stock?">@csrf @cannot('purchases.void')@method('DELETE')@endcannot <p class="muted">All received stock must still be unused. The delivery and payment history will be retained.</p><label class="field">Reason<textarea name="reason" minlength="3" maxlength="1000" required></textarea></label><div class="form-footer"><button type="button" class="btn secondary" data-close-purchase-dialog>Cancel</button><button class="btn danger">Void purchase</button></div></form>@endif</div></dialog>
@endcanany
@endif
@endsection
@push('scripts')
<script>
const purchaseDialogs = document.querySelectorAll('.purchase-payment-dialog');
document.querySelectorAll('#purchase-pay-dialog input[name=amount]').forEach(input=>input.addEventListener('input',()=>{ const note=input.closest('form').querySelector('.purchase-payment-change'); const change=Math.max(0,Number(input.value)-Number(input.dataset.due)); note.hidden=change<=0; note.querySelector('strong').textContent=change.toFixed(2); }));
function openPurchaseDialog(id) { const dialog=document.getElementById(id); if(!dialog)return; dialog.showModal(); requestAnimationFrame(()=>{ const input=dialog.querySelector('input[type="number"]'); input?.focus(); input?.select(); }); }
document.querySelectorAll('[data-purchase-dialog]').forEach(button=>button.addEventListener('click',()=>openPurchaseDialog(button.dataset.purchaseDialog)));
document.querySelectorAll('[data-close-purchase-dialog]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
@if($errors->any() && old('payment_action'))
openPurchaseDialog({{ \Illuminate\Support\Js::from(match(old('payment_action')){'REFUND'=>'purchase-refund-dialog','BALANCE'=>'purchase-balance-dialog',default=>'purchase-pay-dialog'}) }});
@elseif(request()->boolean('payment'))
openPurchaseDialog({{ \Illuminate\Support\Js::from($purchase->payment_tracking?'purchase-pay-dialog':'purchase-balance-dialog') }});
@endif
</script>
@endpush
