<section class="card conversion-card">
    <input type="hidden" name="conversions_present" value="1">
    <div class="conversion-heading"><div><span class="eyebrow">SELL IN MORE WAYS</span><h2>{{ $product?'Additional units & conversions':'Unit conversions' }}</h2><p>Set an exact relationship, such as 12 pieces = 1 dozen, or 1 kg = 1,000 g.</p></div><div class="heading-actions">@if($product)<select id="unit-preset" aria-label="Load unit preset"><option value="">Load a preset</option>@foreach($presets as $preset)<option value="{{ $preset->id }}" data-base="{{ $preset->unit_id }}">{{ $preset->name }}</option>@endforeach</select>@endif<button type="button" class="btn secondary" id="add-conversion"><x-icon name="plus"/>Add unit</button></div></div>
    <div id="unit-editor-message" class="notice amber" role="status" hidden></div>
    <div id="conversion-rows"></div>
    <div id="conversion-empty" class="conversion-empty"><span class="customer-section-icon"><x-icon name="ruler"/></span><strong>{{ $product?'Selling in the primary unit only':'Build a reusable unit group' }}</strong><p>Add a unit to set its conversion{{ $product?' and selling price':'' }}.</p></div>
    @if($product)<div class="conversion-note"><x-icon name="info" :size="16"/><span>Leave the additional selling price empty to calculate it from the primary price. Override it for pack or bulk pricing. Decimal stock conversions round to your configured quantity precision.</span></div>@endif
</section>
<template id="conversion-template"><div class="conversion-row">
    <div class="conversion-equation"><label class="field"><span>Primary quantity</span><div class="conversion-base"><input data-field="base_quantity" type="number" min="0.000001" max="999999" step="0.000001" inputmode="decimal" value="1" required><span data-base-label>Primary</span></div></label><span class="conversion-equals">=</span><label class="field"><span>Additional quantity</span><input data-field="converted_quantity" type="number" min="0.000001" max="999999" step="0.000001" inputmode="decimal" value="1" required></label><label class="field"><span>Additional unit</span><select data-field="unit_id" required><option value="">Select unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }} ({{ $unit->short_name }})</option>@endforeach</select></label></div>
    @if($product)<label class="field conversion-price"><span>Selling price / additional unit</span><input data-field="price" type="number" min="0" max="999999999" step="0.01" inputmode="decimal" placeholder="Calculated"><small data-calculated-price>Calculated from the primary price</small></label>@endif
    <button type="button" class="icon-button text-danger remove-conversion" aria-label="Remove additional unit" title="Remove unit"><x-icon name="trash-2"/></button>
</div></template>
<script type="application/json" id="conversion-initial">{!! json_encode(old('conversions',$record->conversions->map(fn($row)=>$row->only($product?['unit_id','base_quantity','converted_quantity','price']:['unit_id','base_quantity','converted_quantity']))->all()),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
@if($product)<script type="application/json" id="conversion-presets">{!! json_encode($presets->map(fn($p)=>['id'=>$p->id,'unit_id'=>$p->unit_id,'conversions'=>$p->conversions->map(fn($r)=>$r->only('unit_id','base_quantity','converted_quantity'))->all()]),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>@endif
