@extends('layouts.app')
@section('title','Sales Return')
@section('content')
<div class="page-heading"><div><span class="eyebrow">RETURNS & EXCHANGES</span><h1>Sales Return</h1><p>Search an original bill or continue without a bill.</p>@if($draft)<span class="badge amber">Draft {{ $draft->reference }}</span>@endif</div><div class="heading-actions return-heading-actions">@can('sales_returns.view')<a class="btn secondary" href="{{ route('returns.index','sales') }}">Return history</a>@endcan<button class="btn secondary" type="button" id="nr-save-draft">Save draft</button></div></div>
@include('returns.mode-tabs',['withoutBill'=>true])
<div class="notice info">No original bill is linked to this return. Some historical price, payment and stock information may need verification.</div>
<ol class="return-stepper" aria-label="Return progress">@foreach(['Products','Return details','Resolution','Settlement'] as $label)<li data-nr-indicator="{{ $loop->iteration }}" class="{{ $loop->first?'active':'' }}"><span>{{ $loop->iteration }}</span>{{ $label }}</li>@endforeach</ol>
<div id="nr-error" class="notice error" role="alert" hidden></div>
<section class="card padded" data-nr-step="1">
    <h2>Customer and returned products</h2>
    <p class="muted">Choose a customer to find possible original purchases, or continue as a walk-in.</p>
    <div class="return-search mt-6"><label class="field">Customer (optional)<input type="search" id="nr-customer-search" placeholder="Search customer name, phone or ID" autocomplete="off"></label><button class="btn secondary" type="button" id="nr-walk-in">Walk-in Customer</button></div>
    <div id="nr-customer-results" class="return-product-results"></div><div id="nr-customer-summary" class="notice info mt-6">Walk-in Customer · Select a customer to use account credit or add an exchange difference to due.</div>
    <div class="form-grid mt-6"><label class="field">Category<select id="nr-category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label class="field">Returned product search<input type="search" id="nr-product-search" placeholder="Search or scan product..." autocomplete="off"></label></div>
    <div id="nr-product-results" class="return-product-results"></div>
    <h3 class="mt-6">Returned Items</h3><div id="nr-added-products" class="nr-added-products"><p class="muted">Search or scan a product to start.</p></div>
    <div class="form-footer"><button class="btn primary" type="button" data-nr-next="2">Continue to return details<x-icon name="arrow-right"/></button></div>
</section>
<section class="card padded" data-nr-step="2" hidden>
    <h2>Returned items & stock actions</h2>
    <div class="form-grid mt-6"><label class="field">Main return reason<select id="nr-reason"><option value="">Choose a reason</option>@foreach(['Damaged','Defective','Wrong item','Expired','Customer changed mind','Product quality issue','Other'] as $reason)<option>{{ $reason }}</option>@endforeach</select></label><label class="field">Reason / notes<textarea id="nr-notes" maxlength="2000" placeholder="Add details (required for Other)"></textarea></label></div>
    <div id="nr-lines" class="mt-6"></div>
    <div class="form-footer"><button class="btn secondary" type="button" data-nr-next="1">Add another product / customer</button><button class="btn primary" type="button" data-nr-next="3">Choose resolution<x-icon name="arrow-right"/></button></div>
</section>
<section class="card padded" data-nr-step="3" hidden>
    <h2>What should the customer receive?</h2>
    <div class="return-resolution-grid">@foreach(['SAME'=>['package','Same Product'],'OTHER'=>['shopping-bag','Another Product'],'MONEY'=>['banknote','Money / Account Credit']] as $value=>[$icon,$label])<label class="return-resolution"><input type="radio" name="nr-resolution" value="{{ $value }}" @checked($value==='MONEY')><x-icon :name="$icon" :size="26"/><strong>{{ $label }}</strong></label>@endforeach</div>
    @if(!($settings['no_receipt_cash_refund']??false))<p class="notice info">Cash refunds without a receipt are disabled. You can exchange products, apply credit to a selected customer's due, or use an enabled noncash refund method.</p>@endif
    <div id="nr-replacement-search" hidden><label class="field">Replacement product search<input type="search" id="nr-replacement-query" placeholder="Search products or scan replacement barcode..." autocomplete="off"></label><div id="nr-replacement-results" class="return-product-results"></div></div><div id="nr-replacements" class="mt-6"></div>
    <div class="form-footer"><button class="btn secondary" type="button" data-nr-next="2">Back</button><button class="btn primary" type="button" data-nr-next="4">Review & settle<x-icon name="arrow-right"/></button></div>
</section>
<section data-nr-step="4" hidden><div class="return-review-grid">
    <article class="card padded"><span class="eyebrow">RETURN SUMMARY</span><h2>No-receipt sales return</h2><span id="nr-verification" class="badge amber">No Receipt</span><div id="nr-review-items" class="mt-6"></div><div id="nr-review-totals" class="summary-lines mt-6"></div><div id="nr-allocation-preview" class="mt-6"></div><div id="nr-difference" class="return-difference">Reviewing return...</div></article>
    <article class="card padded"><h2>Settle the difference</h2><p class="muted">Only confirmed original purchases reduce their original bill due automatically. Unverified credit changes customer due only when you choose an amount below.</p>
    <div id="nr-credit-options" class="mt-6">@can('sales_returns.apply_customer_due')<label class="field">Apply credit to selected customer's due<input type="number" id="nr-apply-due" value="0" min="0" step="0.01" disabled></label><small id="nr-due-help">Select a customer in Products to apply account credit.</small>@endcan</div>
    <div id="nr-pay-options" class="mt-6" hidden>@can('pos.due_sale')<label class="check-card"><input type="checkbox" id="nr-add-due" disabled>Add difference to selected customer's due</label>@endcan</div>
    <label class="field mt-6" id="nr-method-label">Payment / refund method<select id="nr-payment-method"><option value="">Choose a method</option>@foreach($methods as $method)<option value="{{ $method->id }}" data-type="{{ $method->type }}" @selected($method->id===($settings['return_default_method']??$methods->firstWhere('type','CASH')?->id))>{{ $method->name }}</option>@endforeach</select></label>
    <p id="nr-settlement-message" class="notice info mt-6"></p><div class="form-footer"><button class="btn secondary" type="button" data-nr-next="3">Back</button><button class="btn primary" type="button" id="nr-complete" disabled><x-icon name="check"/>Complete Return</button></div>
    </article></div></section>
<dialog id="nr-price-dialog" class="sale-dialog"><div class="modal-heading"><h2>Choose replacement selling price</h2><button class="icon-button" type="button" id="nr-price-close" aria-label="Close price selector"><x-icon name="x"/></button></div><div id="nr-price-options" class="sale-dialog-body"></div></dialog>
<script type="application/json" id="no-receipt-config">{!! json_encode(['token'=>$draft?->token??(string)\Illuminate\Support\Str::uuid(),'draft'=>$draft?->draft_payload,'productsUrl'=>route('returns.no-receipt.products','sales'),'replacementProductsUrl'=>route('returns.products','sales'),'customersUrl'=>route('returns.no-receipt.customers','sales'),'matchesUrl'=>route('returns.no-receipt.matches','sales'),'quoteUrl'=>route('returns.quote','sales'),'storeUrl'=>route('returns.store','sales'),'draftUrl'=>route('returns.draft','sales'),'suppliers'=>$suppliers->map(fn($s)=>['id'=>$s->id,'name'=>$s->name]),'currency'=>$settings['currency_symbol']??'Rs.','autoHistory'=>$settings['no_receipt_auto_history']??true,'requireReason'=>$settings['return_require_reason']??true,'requireCustomer'=>($settings['no_receipt_require_customer']??false)||!($settings['return_allow_anonymous']??true),'daysLimit'=>$settings['no_receipt_days_limit']??0,'costMethod'=>$settings['no_receipt_cost_method']??'LATEST_PURCHASE','priceRule'=>$settings['no_receipt_credit_price']??'CURRENT_LOWEST','defaultAction'=>$settings['return_default_stock_action']??'RESTOCK','allowPriceChange'=>($settings['no_receipt_allow_price_change']??true)&&(auth()->user()->hasPermission('sales_returns.no_receipt_price_override')||auth()->user()->hasPermission('sales_returns.override_credit_price')),'manualPrice'=>auth()->user()->hasPermission('sales_returns.no_receipt_price_override')||auth()->user()->hasPermission('sales_returns.override_credit_price'),'viewCost'=>auth()->user()->hasPermission('returns.view_cost'),'writeoff'=>auth()->user()->hasPermission('sales_returns.writeoff'),'supplierReturn'=>auth()->user()->hasPermission('sales_returns.return_to_supplier')&&auth()->user()->hasPermission('sales_returns.no_receipt_supplier'),'cashRefundAllowed'=>($settings['no_receipt_cash_refund']??false)&&auth()->user()->hasPermission('sales_returns.no_receipt_cash_refund')],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
@endsection
