<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $document->reference }} · Credit note</title><style>body{font:12px monospace;margin:20px auto;width:72mm;color:#000}h1,h2{text-align:center;font-size:16px}p{margin:6px 0}.row{display:flex;justify-content:space-between;gap:8px}.rule{border-top:1px dashed #000;margin:10px 0}.controls{display:flex;gap:8px;margin-bottom:20px}button,a{font:14px sans-serif} @page{size:80mm auto;margin:4mm}@media print{body{margin:0;width:72mm}.controls{display:none}}</style></head><body>
<div class="controls"><button onclick="window.print()">Print</button><a href="{{ route('returns.show',[$kind,$document->id]) }}">Back</a></div>
@if(!empty($settings['logo']) && ($settings['show_logo_receipt']??true))<img src="{{ asset('storage/'.$settings['logo']) }}" alt="Logo" style="display:block;max-width:32mm;max-height:20mm;margin:auto">@endif
<h1>{{ $settings['business_name']??'Twinsofte Supermarket' }}</h1><p style="text-align:center">{{ $settings['address']??'' }}<br>{{ $settings['phone']??'' }}</p><h2>{{ $kind==='sales'?'SALES RETURN':'PURCHASE RETURN' }}</h2><p>Return No: {{ $document->reference }}<br>Original Bill: {{ $kind==='sales'?$document->sale->invoice:$document->purchase->reference }}<br>Date: {{ $document->returned_at->format('d/m/Y h:i A') }}<br>Cashier: {{ $document->user->name }}<br>Status: {{ $document->status }}</p><div class="rule"></div>
@foreach($document->items as $line)<p><strong>{{ $line->item->name }}</strong><br>{{ $line->quantity }} {{ $line->item->unit }} @if($kind==='sales') · {{ match($line->stock_action){'RESTOCK'=>'Restocked','WRITEOFF'=>'Write off',default=>'Supplier return'} }}@endif</p><div class="row"><span>Return value</span><strong>{{ \App\Support\Money::display($line->amount) }}</strong></div>@endforeach
<div class="rule"></div><p>Resolution: {{ match($document->resolution){'SAME'=>'Same product','OTHER'=>'Another product',default=>'Money / credit back'} }}</p>@if($document->replacement)<p>Replacement bill: {{ $kind==='sales'?$document->replacement->invoice:$document->replacement->reference }}</p>@foreach($document->replacement->items as $line)<div class="row"><span>{{ $line->name }} × {{ $line->quantity }}</span><span>{{ \App\Support\Money::display($line->total) }}</span></div>@endforeach @endif<div class="rule"></div>
@foreach(['amount'=>'Return value','due_reduction'=>'Original due reduced','replacement_value'=>'Replacement value',($kind==='sales'?'customer_due_applied':'supplier_due_applied')=>'Other due reduced','refund_amount'=>$kind==='sales'?'Customer refund':'Supplier refund received','additional_payment'=>$kind==='sales'?'Customer paid':'Paid to supplier'] as $field=>$label)<div class="row"><span>{{ $label }}</span><strong>{{ \App\Support\Money::display($document->$field??0) }}</strong></div>@endforeach
@if($kind==='purchase')<div class="row"><span>Supplier credit</span><strong>{{ \App\Support\Money::display($document->supplier_credit) }}</strong></div>@endif
@foreach($document->settlements as $event)<p>{{ $event->method_name }} · {{ str_replace('_',' ',$event->kind) }}: {{ \App\Support\Money::display($event->amount) }}</p>@endforeach<div class="rule"></div><p>{{ $document->reason }}</p>@if($document->cancel_reason)<p>Cancelled: {{ $document->cancel_reason }}</p>@endif<p style="text-align:center">{{ $settings['receipt_footer']??'Thank you.' }}</p>
@if(($settings['return_auto_print']??false) && request('print')==='1')<script>window.addEventListener('load',()=>window.print());</script>@endif
</body></html>
