@extends('layouts.app')
@section('title',$document->reference)
@section('content')
@php($currency=$settings['currency_symbol']??'Rs.')
<div class="page-heading"><div><span class="eyebrow">{{ $kind==='sales'?'SALES RETURN':'PURCHASE RETURN' }}</span><h1>{{ $document->reference }}</h1><p>{{ $document->returned_at->format('d/m/Y h:i A') }} · {{ $document->user->name }}</p></div><div class="heading-actions return-heading-actions">@can($kind.'_returns.view')<a class="btn secondary" href="{{ route('returns.index',$kind) }}">Return history</a>@endcan<a class="btn primary" href="{{ route('returns.receipt',[$kind,$document->id]) }}"><x-icon name="printer"/>80mm credit note</a></div></div>
@if($document->status==='DRAFT')<div class="notice info">This draft has no stock or financial effect.</div><a class="btn primary mb-6" href="{{ route('returns.create',[$kind,'draft_id'=>$document->id]) }}">Continue draft</a>@endif
<div class="return-review-grid"><article class="card padded"><span class="badge {{ $document->status==='COMPLETED'?'green':'slate' }}">{{ $document->status }}</span><h2 class="mt-6">Original bill <a class="text-link" href="{{ route($kind==='sales'?'sales.show':'purchases.show',$kind==='sales'?$document->sale_id:$document->purchase_id) }}">{{ $kind==='sales'?$document->sale->invoice:$document->purchase->reference }}</a></h2><p>{{ $document->reason }}@if($document->notes) · {{ $document->notes }}@endif</p><div class="table-scroll mt-6"><table><thead><tr><th>Product</th><th>Qty</th><th>Value</th>@if($kind==='sales')<th>Stock action</th>@endif @can('returns.view_cost')<th>Historical cost</th>@endcan</tr></thead><tbody>@foreach($document->items as $line)<tr><td>{{ $line->item->name }}</td><td>{{ $line->quantity }} {{ $line->item->unit }}</td><td>{{ \App\Support\Money::display($line->amount) }}</td>@if($kind==='sales')<td>{{ match($line->stock_action){'RESTOCK'=>'Restocked','WRITEOFF'=>'Write off',default=>'Supplier return pending'} }}</td>@endif @can('returns.view_cost')<td>{{ \App\Support\Money::display($line->cost_total) }}</td>@endcan</tr>@endforeach</tbody></table></div>
@if($document->replacement)<h3 class="mt-6">Replacement {{ $document->resolution==='SAME'?'(same product)':'products' }}</h3><a class="text-link" href="{{ route($kind==='sales'?'sales.show':'purchases.show',$document->replacement) }}">{{ $kind==='sales'?$document->replacement->invoice:$document->replacement->reference }}</a>@foreach($document->replacement->items as $line)<p>{{ $line->name }} × {{ $line->quantity }} {{ $line->unit }} · {{ \App\Support\Money::display($line->total) }}</p>@endforeach @endif
@if($document->allocations->isNotEmpty())<h3 class="mt-6">Account credit allocations</h3>@foreach($document->allocations as $a)<p>{{ str_replace('_',' ',$a->kind) }} · {{ $a->sale?->invoice??$a->purchase?->reference??('Customer #'.$a->customer_id) }} · {{ \App\Support\Money::display($a->amount) }} · {{ $a->status }}</p>@endforeach @endif
@if($kind==='sales' && $document->supplierReturns()->exists())@can('supplier_returns.view')<a class="btn secondary mt-6" href="{{ route('returns.suppliers') }}">View linked supplier returns</a>@endcan @endif
@can('returns.view_cost')<details class="mt-6"><summary>Original stock allocations</summary>@foreach($document->items as $item)@foreach($item->allocations as $a)<p>Layer #{{ $a->stock_layer_id }} · {{ $a->layer->source_reference }} · {{ $a->quantity }} primary units · cost {{ \App\Support\Money::display($a->cost_total) }}@if($a->sale_stock_allocation_id) · original sale allocation #{{ $a->sale_stock_allocation_id }}@endif</p>@endforeach @endforeach</details>@endcan
</article><article class="card padded"><h2>Settlement</h2><div class="summary-lines mt-6">@foreach(['amount'=>'Returned items','fee_refund'=>'Refunded original fees','due_reduction'=>'Original bill due reduced','replacement_value'=>'Replacement value',($kind==='sales'?'customer_due_applied':'supplier_due_applied')=>'Other due reduced','refund_amount'=>$kind==='sales'?'Money refunded':'Money received','additional_payment'=>$kind==='sales'?'Customer paid':'Paid to supplier'] as $key=>$label)<div><span>{{ $label }}</span><strong>{{ $currency }} {{ \App\Support\Money::display($document->$key??0) }}</strong></div>@endforeach @if($kind==='purchase')<div><span>Supplier credit retained</span><strong>{{ $currency }} {{ \App\Support\Money::display($document->supplier_credit) }}</strong></div>@endif</div><h3 class="mt-6">Money movements</h3>@forelse($document->settlements as $event)<p>{{ str_replace('_',' ',$event->kind) }} · {{ $event->method_name }} · {{ $currency }} {{ \App\Support\Money::display($event->amount) }} <small>{{ $event->created_at->format('d/m/Y h:i A') }}</small></p>@empty<p>No money movement required.</p>@endforelse
@if($document->status==='CANCELLED')<div class="notice info mt-6">Cancelled {{ $document->cancelled_at->format('d/m/Y h:i A') }} · {{ $document->cancel_reason }}</div>@else @can($kind.'_returns.cancel')<details class="mt-6"><summary>Cancel return</summary><p class="muted">This reverses the recorded stock and settlements. Used replacement stock or sent supplier returns prevent cancellation.</p><form method="POST" action="{{ route('returns.cancel',[$kind,$document->id]) }}" data-confirm="Cancel this return and reverse its stock and financial movements?">@csrf<label class="field">Cancellation reason<textarea name="reason" required minlength="3" maxlength="1000"></textarea></label><button class="btn danger mt-6">Cancel return</button></form></details>@endcan @endif
</article></div>
@endsection
