@extends('layouts.app')
@section('title',$adjustment->exists?'Edit stock adjustment':'New stock adjustment')
@section('content')
<div class="page-heading"><div><span class="eyebrow">INVENTORY</span><h1>{{ $adjustment->exists?'Edit adjustment':'New stock adjustment' }}</h1><p>{{ $adjustment->exists?$adjustment->reference.' · Revision '.$adjustment->revision:'Select products and apply your corrections in one batch.' }}</p></div><a class="btn secondary" href="{{ route('adjustments.index') }}"><x-icon name="arrow-left"/>Back to history</a></div>
<form id="adjustment-form" method="POST" action="{{ $adjustment->exists?route('adjustments.update',$adjustment):route('adjustments.store') }}" data-can-cost="{{ auth()->user()->hasPermission('products.view_cost')?'1':'0' }}" data-can-prices="{{ auth()->user()->hasPermission('products.manage_prices')?'1':'0' }}" data-products-url="{{ route('adjustments.products') }}" data-currency="{{ $settings['currency_symbol']??'Rs.' }}" data-precision="{{ $settings['quantity_decimals']??3 }}">
@csrf @if($adjustment->exists)@method('PUT')<input type="hidden" name="revision" value="{{ $adjustment->revision }}">@endif
<div class="card adjustment-intro"><label class="field"><span>Reason <span class="required-mark">*</span></span><input name="reason" required minlength="3" maxlength="255" value="{{ old('reason',$adjustment->reason) }}" placeholder="Stock count, damaged goods, price correction…"></label><p class="muted text-sm">Quantities, selling prices and costs use each product’s primary stock unit. Select a stock price row when removing stock. Added stock receives its own cost and selling price; leaving these blank uses the product defaults. Use Purchases for deliveries.</p>@if($adjustment->exists)<p class="notice info">Changes below apply to the current inventory. Original products stay in this batch; previous revisions remain in the audit log.</p>@endif</div>
<div class="card mt-6"><div class="card-heading"><div><h2>Choose products</h2><p class="muted text-sm">Select several products, then add them together.</p></div><span id="adjustment-search-count" class="badge slate"></span></div><div class="adjustment-search"><label class="search-field"><x-icon name="search"/><input type="search" id="adjustment-search" maxlength="255" placeholder="Search name, SKU or barcode…" aria-label="Search adjustment products"></label><div class="adjustment-selection-tools"><label class="inline-check"><input type="checkbox" id="adjustment-select-all">Select all results</label><button class="btn secondary" type="button" id="adjustment-add-selected" disabled><x-icon name="plus"/>Add selected</button></div></div><div id="adjustment-search-results" class="adjustment-product-grid"></div><div id="adjustment-message" class="notice error" role="alert" hidden></div></div>
<div class="card mt-6"><div class="card-heading"><h2>Adjustment items</h2><span id="adjustment-row-count" class="badge green">0 products</span></div><div class="table-wrap"><table class="adjustment-items-table"><thead><tr><th>Product / unit</th><th>Current stock</th><th>Adjustment</th><th>Quantity</th><th>New stock</th><th>Selling price (optional)</th>@can('products.view_cost')<th>Cost (optional)</th>@endcan<th></th></tr></thead><tbody id="adjustment-items"></tbody></table></div><div id="adjustment-empty" class="empty-state"><x-icon name="package" :size="32"/><h3>Select products above</h3><p>Change quantities, selling prices or costs as needed.</p></div></div>
<div class="adjustment-form-actions"><a class="btn secondary" href="{{ route('adjustments.index') }}">Cancel</a><button class="btn primary" id="adjustment-save" type="submit"><x-icon name="check"/>{{ $adjustment->exists?'Save revision':'Apply adjustment' }}</button></div>
</form>
<script type="application/json" id="adjustment-initial-rows">{!! json_encode($rows,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) !!}</script>
@endsection
@push('scripts')@vite('resources/js/stock-adjustments.js')@endpush
