@extends('layouts.app')
@section('title',$adjustment->reference)
@section('content')
<div class="page-heading"><div><span class="eyebrow">STOCK ADJUSTMENT · REVISION {{ $adjustment->revision }}</span><h1>{{ $adjustment->reference }}</h1><p>{{ $adjustment->reason }}</p></div><div class="heading-actions"><a class="btn secondary" href="{{ route('adjustments.index') }}"><x-icon name="arrow-left"/>History</a><button class="btn secondary" type="button" onclick="window.print()"><x-icon name="printer"/>Print / save PDF</button>@if($adjustment->status==='ACTIVE')@can('stock-adjustments.edit')<a class="btn secondary" href="{{ route('adjustments.edit',$adjustment) }}"><x-icon name="pencil"/>Edit adjustment</a>@endcan @can('stock-adjustments.delete')<button type="button" class="btn danger" id="open-adjustment-reverse"><x-icon name="ban"/>Reverse adjustment</button>@endcan @endif</div></div>
<div class="card adjustment-detail-meta"><div><span class="muted">Status</span><strong><span class="badge {{ $adjustment->status==='ACTIVE'?'green':'slate' }}">{{ $adjustment->status==='ACTIVE'?'Applied':'Reversed' }}</span></strong></div><div><span class="muted">Created by</span><strong>{{ $adjustment->user->name }}</strong></div><div><span class="muted">Created</span><strong>{{ $adjustment->created_at->format('d/m/Y H:i') }}</strong></div><div><span class="muted">Last updated</span><strong>{{ $adjustment->updated_at->format('d/m/Y H:i') }}</strong></div></div>
@if($adjustment->status==='VOID')<div class="notice info mt-6">Reversed by {{ $adjustment->voider?->name }} on {{ $adjustment->voided_at->format('d/m/Y H:i') }}. {{ $adjustment->void_reason }}</div>@endif
<div class="card mt-6"><div class="card-heading"><h2>{{ $adjustment->items->count() }} adjusted products</h2><span class="muted text-sm">Saved snapshots · quantities in primary units</span></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Original stock</th><th>Net change</th><th>Stock at last revision</th><th>Selling price</th>@can('products.view_cost')<th>Cost</th>@endcan</tr></thead><tbody>@foreach($adjustment->items as $item)<tr><td><strong>{{ $item->name }}</strong><div class="muted text-xs">{{ $item->sku }} · {{ $item->unit }}</div></td><td>{{ $item->stock_before }} {{ $item->unit }}</td><td>{{ \App\Support\Money::compare($item->quantity_change,0)>0?'+':'' }}{{ $item->quantity_change }} {{ $item->unit }}</td><td>{{ $item->stock_after }} {{ $item->unit }}</td><td>{{ \App\Support\Money::display($item->price_before) }}@if($item->price_changed)<span class="muted"> → </span><strong>{{ \App\Support\Money::display($item->price_after) }}</strong>@else <span class="muted text-xs">unchanged</span>@endif</td>@can('products.view_cost')<td>{{ \App\Support\Money::display($item->cost_before) }}@if($item->cost_changed)<span class="muted"> → </span><strong>{{ \App\Support\Money::display($item->cost_after) }}</strong>@else <span class="muted text-xs">unchanged</span>@endif</td>@endcan</tr>@endforeach</tbody></table></div></div>
<p class="muted text-sm mt-6">Subsequent sales, purchases and corrections may change live stock. Revision and reversal details are retained in the audit log.</p>
@if($adjustment->status==='ACTIVE')@can('stock-adjustments.delete')
<dialog id="adjustment-reverse-dialog" class="line-editor-dialog" aria-labelledby="adjustment-reverse-title"><div class="modal-heading"><div><span class="eyebrow">REVERSE CORRECTION</span><h2 id="adjustment-reverse-title">Reverse adjustment?</h2></div><button type="button" class="icon-button" id="close-adjustment-reverse" aria-label="Close reversal"><x-icon name="x"/></button></div><form class="line-editor-body" method="POST" action="{{ route('adjustments.destroy',$adjustment) }}">@csrf @method('DELETE')<input type="hidden" name="revision" value="{{ $adjustment->revision }}"><p class="muted">This reverses this batch’s net quantity changes and restores prices changed by it. History will remain. Newer price changes or insufficient stock will prevent reversal.</p><label class="field"><span>Reason</span><input name="reason" required minlength="3" maxlength="255" placeholder="Why is this adjustment being reversed?"></label><div class="line-editor-footer"><button class="btn secondary" type="button" id="cancel-adjustment-reverse">Keep adjustment</button><button class="btn danger" type="submit">Reverse adjustment</button></div></form></dialog>
@endcan @endif
@endsection
@push('scripts')@vite('resources/js/stock-adjustments.js')@endpush
