@extends('layouts.app')
@section('title','Daily register')
@section('content')<div class="page-heading"><div><span class="eyebrow">YOUR SHIFT</span><h1>Daily register</h1><p>Start your shift, track cash, and close with confidence.</p></div>@can('pos.access')<a class="btn primary" href="{{ route('pos.index') }}"><x-icon name="scan-line"/>Open POS</a>@endcan</div>
@if(!$register)
<div class="card padded register-start-card"><span class="register-welcome-icon"><x-icon name="wallet" :size="28"/></span><h2>Ready to start your shift?</h2><p class="muted">Enter your opening cash in the register popup.</p>@can('register.open')<button type="button" class="btn primary" data-open-register>Open register</button>@endcan</div>
@else
<div class="stat-grid">@foreach(['Opening cash'=>$register->opening_cash,'Cash sales'=>$summary['cash'],'Customer collections'=>$summary['collections'],'Expected cash'=>$summary['expected']] as $label=>$amount)<div class="card stat-card"><div class="stat-top">{{ $label }}</div><strong>{{ $settings['currency_symbol']??'Rs.' }} {{ \App\Support\Money::display($amount) }}</strong></div>@endforeach</div>
<div class="card padded mt-6 register-shift-actions"><div><h2>REG-{{ $register->id }} · Current shift</h2><p class="muted">Review all sales, payment methods and fees before closing.</p></div><button class="btn primary" type="button" data-close-register>Review & close register</button></div>
@can('register.close')<form method="POST" action="{{ route('register.movement') }}" class="card form-card mt-6">@csrf<h2>Cash movement</h2><label class="field">Movement type<select name="type"><option value="IN">Cash in</option><option value="OUT">Cash out</option></select></label><label class="field">Amount<input type="number" name="amount" min="0.01" step="0.01" required></label><label class="field">Description<input name="description" required maxlength="255"></label><button class="btn secondary">Record movement</button></form>@endcan
<div class="card mt-6"><div class="card-heading"><h2>Current cash movements</h2></div><div class="table-wrap"><table><thead><tr><th>Time</th><th>Type</th><th>Description</th><th>Amount</th></tr></thead><tbody>@forelse($register->movements as $m)<tr><td>{{ $m->created_at->format('H:i') }}</td><td>{{ $m->type }}</td><td>{{ $m->description }}</td><td>{{ \App\Support\Money::display($m->amount) }}</td></tr>@empty<tr><td colspan="4" class="empty-cell">No cash movements.</td></tr>@endforelse</tbody></table></div></div>
@endif
<div class="card mt-6"><div class="card-heading"><h2>Register history</h2></div><div class="table-wrap"><table><thead><tr><th>Register</th><th>Opened</th><th>Closed</th><th>Expected</th><th>Actual</th><th>Difference</th><th>Summary</th></tr></thead><tbody>@forelse($registers as $r)<tr><td>REG-{{ $r->id }}</td><td>{{ $r->opened_at->format('d/m/Y H:i') }}</td><td>{{ $r->closed_at?->format('d/m/Y H:i')??'Open' }}</td><td>{{ $r->expected_cash!==null?\App\Support\Money::display($r->expected_cash):'—' }}</td><td>{{ $r->actual_cash!==null?\App\Support\Money::display($r->actual_cash):'—' }}</td><td>{{ $r->difference!==null?\App\Support\Money::display($r->difference):'—' }}</td><td><a class="text-link" href="{{ route('register.show',$r) }}">View</a></td></tr>@empty<tr><td colspan="7" class="empty-cell">No registers opened yet.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $registers->links() }}</div></div>@endsection
