@extends('layouts.app')
@section('title','Profit & loss')
@section('main-class','report-workspace')
@section('content')
<div class="page-heading"><div><span class="eyebrow">BUSINESS PERFORMANCE</span><h1>Profit & loss</h1><p>{{ $filters['from'] }} to {{ $filters['to'] }} · {{ $settings['currency']??'LKR' }}</p></div><div class="heading-actions"><a class="btn secondary" href="{{ route('reports.index') }}">All reports</a>@can('reports.profit.pdf')<a class="btn primary" href="{{ route('reports.pdf',['report'=>'profit']+$filters) }}"><x-icon name="download"/>Download PDF</a>@endcan<button class="btn secondary" onclick="window.print()"><x-icon name="printer"/>Print</button></div></div>
<x-sales-visibility-note/>
<div class="stat-grid mb-6">@foreach(['revenue'=>'Sales revenue','gross'=>'Gross profit','net'=>'Net profit'] as $key=>$label)<div class="card stat-card"><div class="stat-top">{{ $label }}</div><strong>{{ $settings['currency_symbol']??'Rs.' }} {{ \App\Support\Money::display($summary[$key]) }}</strong></div>@endforeach</div>
<div class="card report-data-card profit-statement"><div class="card-heading"><div><h2>Income statement</h2><p class="muted">Revenue, inventory costs and operating expenses for this period.</p></div><span class="tile-icon"><x-icon name="trending-up"/></span></div><form class="filter-bar report-filter-bar" method="GET"><label class="field compact">From<input type="date" name="from" value="{{ $filters['from'] }}" required></label><label class="field compact">To<input type="date" name="to" value="{{ $filters['to'] }}" required></label><button class="btn secondary">Apply filters</button><a class="text-link" href="{{ route('reports.show','profit') }}">Reset</a></form><div class="profit-lines">@foreach(['revenue'=>'Sales revenue','cogs'=>'Cost of goods sold','gross'=>'Gross profit','manual'=>'Other operating expenses','processing'=>'Business-paid processing expenses','purchaseCharges'=>'Purchase shipping & other charges','expenses'=>'Total operating expenses','net'=>'Net profit'] as $key=>$label)<div class="{{ in_array($key,['gross','net'])?'profit-total':'' }} {{ $key==='net'?'net':'' }}"><span>{{ $label }}</span><strong>{{ $settings['currency_symbol']??'Rs.' }} {{ \App\Support\Money::display($summary[$key]) }}</strong></div>@endforeach</div><p class="muted text-sm p-6">Revenue and inventory costs are net of returns. Customer-paid processing fees are tracked separately from product revenue. Business-paid fees reduce profit once through their linked expenses. Voided sales and reversed expenses are excluded.</p></div>
@endsection
