<?php

return [
    'sales_returns_enabled' => ['Sales returns enabled', 'checkbox', true, 'required|boolean'],
    'purchase_returns_enabled' => ['Purchase returns enabled', 'checkbox', true, 'required|boolean'],
    'return_default_stock_action' => ['Default stock action', 'choice', 'RESTOCK', 'required|in:RESTOCK,WRITEOFF,SUPPLIER'],
    'return_default_method' => ['Default refund method', 'payment', null, 'nullable|integer|exists:payment_methods,id'],
    'return_require_reason' => ['Require return reason', 'checkbox', true, 'required|boolean'],
    'return_approval_above' => ['Manager approval above (0 disables)', 'number', '0', 'required|numeric|min:0|max:999999999999|decimal:0,2'],
    'return_allow_anonymous' => ['Allow anonymous sale returns', 'checkbox', true, 'required|boolean'],
    'return_apply_customer_due' => ['Allow return credit to customer due', 'checkbox', true, 'required|boolean'],
    'return_customer_search' => ['Allow customer search for due allocation', 'checkbox', true, 'required|boolean'],
    'return_allow_supplier' => ['Allow return to supplier', 'checkbox', true, 'required|boolean'],
    'return_fee_policy' => ['Payment charge refund policy', 'choice', 'NONE', 'required|in:NONE,FULL,PRO_RATA'],
    'no_receipt_enabled' => ['No-receipt sales returns enabled', 'checkbox', true, 'required|boolean'],
    'no_receipt_credit_price' => ['No-receipt default credit price', 'choice', 'CURRENT_LOWEST', 'required|in:CURRENT_LOWEST,CURRENT_DEFAULT,LATEST_PRICE,MANUAL'],
    'no_receipt_cash_refund' => ['Allow cash refund without receipt', 'checkbox', false, 'required|boolean'],
    'no_receipt_require_customer' => ['Require customer for no-receipt return', 'checkbox', false, 'required|boolean'],
    'no_receipt_require_approval' => ['Require manager approval for no-receipt returns', 'checkbox', false, 'required|boolean'],
    'no_receipt_approval_above' => ['No-receipt manager approval above (0 disables)', 'number', '1000', 'required|numeric|min:0|max:999999999999|decimal:0,2'],
    'no_receipt_allow_price_change' => ['Allow changing no-receipt credit price with permission', 'checkbox', true, 'required|boolean'],
    'no_receipt_max_quantity' => ['Maximum primary quantity per no-receipt line (0 disables)', 'number', '0', 'required|numeric|min:0|max:999999999|decimal:0,3'],
    'no_receipt_auto_history' => ['Search customer history automatically', 'checkbox', true, 'required|boolean'],
    'no_receipt_days_limit' => ['No-receipt return days limit (0 disables)', 'number', '0', 'required|integer|min:0|max:36500'],
    'no_receipt_cost_method' => ['No-receipt returned stock cost method', 'choice', 'LATEST_PURCHASE', 'required|in:LATEST_PURCHASE,CURRENT_DEFAULT,MANUAL'],
    'return_auto_print' => ['Automatically print return receipt', 'checkbox', false, 'required|boolean'],
];
