@extends('layouts.app')
@section('title',($record->exists?'Edit ':'Add ').\Illuminate\Support\Str::singular($def['title']))
@section('content')<div class="page-heading"><div><span class="eyebrow">{{ $def['title'] }}</span><h1>{{ $record->exists?'Edit':'Add' }} {{ \Illuminate\Support\Str::singular(strtolower($def['title'])) }}</h1><p>Enter the details below and save your changes.</p></div><a class="btn secondary" href="{{ route('manage.index',$resource) }}"><x-icon name="arrow-left"/>Back</a></div>
<form method="POST" enctype="multipart/form-data" action="{{ $record->exists?route('manage.update',[$resource,$record->id]):route('manage.store',$resource) }}" class="card form-card wide">@csrf @if($record->exists)@method('PUT')@endif
<div class="form-grid">@foreach($def['fields'] as $key=>$field)@php([$label,$type]=$field) @php($value=old($key,$record->$key)) @if($resource==='payment-rules' && $key==='charge_bearer' && $value===null)@php($value='DEFAULT')@endif @if($resource==='products' && $record->exists && $key==='stock')@continue @endif
@if($type==='checkbox')<label class="check-card"><input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$record->exists?$value:($key==='active')))><span>{{ $label }}</span></label>
@elseif($type==='permissions')<fieldset class="permission-grid full"><legend>{{ $label }}</legend>@foreach($permissions->groupBy(fn($p)=>explode('.',$p->name)[0]) as $group=>$items)<div><h3>{{ ucfirst($group) }}</h3>@foreach($items as $permission)<label class="inline-check"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}" @checked(in_array($permission->id,old('permissions',$record->exists?$record->permissions->pluck('id')->all():[])))>{{ $permission->name }}</label>@endforeach</div>@endforeach</fieldset>
@else<label class="field {{ $type==='textarea'?'full':'' }}">{{ $label }} @if($field[2]??true)<span class="required">*</span>@endif
@if($type==='select' || $type==='options')<select name="{{ $key }}" @required($field[2]??true)><option value="">Select {{ strtolower($label) }}</option>@foreach($type==='select'?$options[$key]:$field[3] as $id=>$name)<option value="{{ $id }}" @selected((string)$value===(string)$id)>{{ $name }}</option>@endforeach</select>
@elseif($type==='textarea')<textarea name="{{ $key }}" rows="3" @required($field[2]??true)>{{ $value }}</textarea>
@else<input name="{{ $key }}" type="{{ in_array($type,['money','quantity','decimal','number'])?'number':$type }}" @if(!in_array($type,['file','password']))value="{{ $value??(in_array($type,['money','quantity','decimal','number']) && ($field[2]??true)?0:($type==='date'?today()->toDateString():'')) }}"@endif @if(in_array($type,['money','quantity','decimal','number']))step="{{ match($type){'quantity'=>'0.001','decimal'=>'0.0001','number'=>'1',default=>'0.01'} }}" @if($key!=='priority')min="0"@endif @endif @if($type==='file')accept="image/png,image/jpeg,image/webp"@endif @if($type==='password')autocomplete="new-password"@endif @required(($field[2]??true) && $type!=='file')>
@endif @if($key==='charge_bearer')<small>Rules can inherit the payment method default or choose a specific payer.</small>@endif @if($key==='unit_id')<small>Whole quantities for pieces; decimals for weight or volume units.</small>@endif @if($key==='stock')<small>Opening stock. Use Purchases for subsequent deliveries.</small>@endif @if($key==='password')<small>At least 10 characters. Required for a new account.</small>@endif @if($key==='image' && $record->image)<img class="image-preview" src="{{ asset('storage/'.$record->image) }}" alt="Current product image">@endif @if($resource==='users' && $key==='username')<small>Letters, numbers, dots, underscores and hyphens. Usernames are unique and case-insensitive.</small>@endif @error($key)<small class="text-danger">{{ $message }}</small>@enderror</label>@endif @endforeach</div>
<div class="form-footer"><a class="btn secondary" href="{{ route('manage.index',$resource) }}">Cancel</a><button class="btn primary"><x-icon name="check"/>Save changes</button></div></form>@endsection
