@extends('layouts.app')
@section('title',\Illuminate\Support\Str::singular($def['title']).' details')
@section('content')
@php($singular=$resource==='roles'?'role':\Illuminate\Support\Str::singular(strtolower($def['title'])))
@php($icon=match($resource){'users'=>'users','roles'=>'shield-check','units'=>'ruler','suppliers'=>'truck','expenses'=>'wallet','categories'=>'tags',default=>'folder-open'})
<div class="page-heading"><div><span class="eyebrow">{{ $def['title'] }}</span><h1>{{ $record->name??$record->reference??'Record #'.$record->id }}</h1><p>Review {{ $singular }} details and manage this record.</p></div><div class="heading-actions"><a class="btn secondary" href="{{ route('manage.index',$resource) }}"><x-icon name="arrow-left"/>{{ $def['title'] }}</a>
@if(!($resource==='expenses' && ($record->type!=='MANUAL' || $record->status!=='ACTIVE')) && !($resource==='roles' && $record->name==='Administrator') && !($resource==='expense-categories' && $record->system))
@can(\App\Support\Resources::permission($resource,'edit'))<a class="btn primary" href="{{ route('manage.edit',[$resource,$record->id]) }}"><x-icon name="pencil"/>Edit {{ $singular }}</a>@endcan
@endif</div></div>
<section class="card module-record-card"><div class="customer-section-heading"><span class="customer-section-icon"><x-icon :name="$icon"/></span><div><h2>{{ ucfirst($singular) }} information</h2><p>Saved details for your store.</p></div>@if($resource==='units' && $record->default_slot===1)<span class="badge green">Default for new products</span>@endif</div>
<dl class="detail-grid">@foreach($def['columns'] as $key=>$label)<div><dt>{{ $label }}</dt><dd>@php($value=data_get($record,$key))@if(is_bool($value))<span class="badge {{ $value?'green':'slate' }}">{{ $value?'Yes':'No' }}</span>@elseif(in_array($key,['amount','cost','price','total','minimum_amount','maximum_amount'])){{ $value!==null?($settings['currency_symbol']??'Rs.').' '.\App\Support\Money::display($value):'—' }}@else{{ $value instanceof \DateTimeInterface?$value->format($settings['date_format']??'d/m/Y'):($value??'—') }}@endif</dd></div>@endforeach</dl>
@if($resource==='roles')<div class="record-permissions"><h2>Permissions <span class="badge green">{{ $record->permissions->count() }}</span></h2><div class="permission-cards">@foreach($record->permissions->groupBy(fn($p)=>explode('.',$p->name)[0]) as $group=>$permissions)<fieldset class="permission-card"><legend>{{ \Illuminate\Support\Str::headline($group) }}</legend>@foreach($permissions as $permission)<div class="permission-option"><x-icon name="check" :size="15"/><span>{{ \Illuminate\Support\Str::headline(explode('.',$permission->name,2)[1]??$permission->name) }}</span></div>@endforeach</fieldset>@endforeach</div></div>@endif
@if($resource==='expenses' && $record->sale)@can('sales.view')<div class="record-permissions"><a class="text-link" href="{{ route('sales.show',$record->sale) }}">Related sale {{ $record->sale->invoice }}<x-icon name="arrow-up-right" :size="15"/></a></div>@endcan @endif
</section>
@endsection
