@extends('layouts.app')
@section('title','Human resources')
@section('content')
<div class="page-heading"><div><span class="eyebrow">YOUR PEOPLE WORKSPACE</span><h1>Human resources</h1><p>Keep your team, attendance and salary records in one place.</p></div>@can('hr.staff.create')<a class="btn primary" href="{{ route('hr.staff.create') }}"><x-icon name="user-plus"/>Add staff</a>@endcan</div>
@include('hr.partials.nav')
<div class="stat-grid hr-stats">@foreach(['active'=>['Active staff','users-round'],'present'=>['Present today','calendar-check'],'pending'=>['Leave awaiting approval','calendar-days'],'payroll'=>['Payroll drafts','wallet']] as $key=>[$label,$icon])@if($counts[$key]!==null)<div class="card stat-card"><div class="stat-top"><span>{{ $label }}</span><span class="stat-icon green"><x-icon :name="$icon"/></span></div><strong>{{ $counts[$key] }}</strong><small>{{ $key==='present'?today()->format('d M Y'):'Current records' }}</small></div>@endif @endforeach</div>
<div class="hr-action-grid">@foreach(['hr.staff.view'=>['Your team','Intake, contact details, employment history and optional user accounts.','hr.staff.index','users-round'],'hr.attendance.view'=>['Mark the day','Record attendance, clock times and overtime without losing past records.','hr.attendance','calendar-check'],'hr.payroll.view'=>['Salary workspace','Prepare a salary breakdown, approve it and track every payment.','hr.payroll.index','wallet'],'hr.ledger.view'=>['Staff accounts','View salary dues and advance balances from each staff profile.','hr.staff.index','book-open']] as $perm=>[$label,$desc,$route,$icon])@if(auth()->user()->hasPermission($perm) && ($perm!=='hr.ledger.view' || auth()->user()->hasPermission('hr.staff.view')))<a class="card hr-action-card" href="{{ route($route) }}"><span class="tile-icon"><x-icon :name="$icon"/></span><h2>{{ $label }}</h2><p>{{ $desc }}</p><span class="text-link">Open workspace <x-icon name="arrow-right" :size="16"/></span></a>@endif @endforeach</div>
@include('hr.partials.report-cards')
@endsection
