@extends('layouts.app')
@section('title',$title.' report')
@section('content')
<div class="page-heading"><div><span class="eyebrow">HR REPORTS</span><h1>{{ $title }}</h1><p>{{ $kind==='staff'?'Complete directory, including inactive and exited staff':($filters['from']??'All history').' to '.($filters['to']??'today') }}</p></div><div class="heading-actions">@can('hr.reports.'.$kind.'.pdf')<a class="btn primary" href="{{ route('hr.reports.download',['kind'=>$kind,'format'=>'pdf']+$filters) }}"><x-icon name="download"/>Download PDF</a>@endcan @can('hr.reports.'.$kind.'.export')<a class="btn secondary" href="{{ route('hr.reports.download',['kind'=>$kind,'format'=>'csv']+$filters) }}">Export CSV</a>@endcan</div></div>@include('hr.partials.nav')
@if($cards)<div class="stat-grid mb-6">@foreach($cards as $label=>$amount)<div class="card stat-card"><div class="stat-top">{{ $label }}</div><strong>{{ $settings['currency_symbol']??'Rs.' }} {{ \App\Support\Money::display($amount) }}</strong></div>@endforeach</div>@endif
<section class="card"><form method="GET" class="hr-report-filter"><div class="hr-quick-ranges">@foreach(['today'=>'Today','yesterday'=>'Yesterday','week'=>'This week','month'=>'This month','last_month'=>'Last month','year'=>'This year','all'=>'All history'] as $k=>$v)<a href="{{ route('hr.reports.show',['kind'=>$kind]+array_merge(array_diff_key($filters,array_flip(['from','to','range'])),['range'=>$k])) }}" class="{{ $filters['range']===$k?'selected':'' }}">{{ $v }}</a>@endforeach</div><div class="filter-bar"><label class="field compact">Range<select name="range"><option value="custom" @selected($filters['range']==='custom')>Custom dates</option>@foreach(['today'=>'Today','yesterday'=>'Yesterday','week'=>'This week','month'=>'This month','last_month'=>'Last month','year'=>'This year','all'=>'All history'] as $k=>$v)<option value="{{ $k }}" @selected($filters['range']===$k)>{{ $v }}</option>@endforeach</select></label><label class="field compact">From<input type="date" name="from" value="{{ $filters['from']??'' }}"></label><label class="field compact">To<input type="date" name="to" value="{{ $filters['to']??'' }}"></label><label class="field compact">Staff<select name="staff_id"><option value="">All staff</option>@foreach($staff as $s)<option value="{{ $s->id }}" @selected(($filters['staff_id']??'')==$s->id)>{{ $s->code }} · {{ $s->name }}</option>@endforeach</select></label><label class="field compact">Department<select name="department_id"><option value="">All departments</option>@foreach($departments as $d)<option value="{{ $d->id }}" @selected(($filters['department_id']??'')==$d->id)>{{ $d->name }}</option>@endforeach</select></label><label class="field compact">Status<select name="status"><option value="">All statuses</option>@foreach(match($kind){'staff'=>['ACTIVE','INACTIVE','EXITED'],'attendance'=>['PRESENT','LATE','ABSENT','HALF_DAY','PAID_LEAVE','UNPAID_LEAVE','HOLIDAY','OFF','UNMARKED'],'leave'=>['PENDING','APPROVED','REJECTED','CANCELLED'],'payroll'=>['DRAFT','APPROVED','VOIDED'],'employment'=>['INTAKE','EXIT','REHIRE','PROFILE_UPDATE'],default=>['ACTIVE','REVERSED']} as $s)<option @selected(($filters['status']??'')===$s)>{{ $s }}</option>@endforeach</select></label><button class="btn secondary">Apply filters</button></div></form><div class="card-heading"><h2>{{ number_format($records->total()) }} matching records</h2><span class="muted">Downloads include every page</span></div><div class="table-wrap"><table><thead><tr>@foreach($headers as $h)<th>{{ $h }}</th>@endforeach</tr></thead><tbody>@forelse($rows as $row)<tr>@foreach($row as $cell)<td>{{ $cell }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($headers) }}" class="empty-cell">No records match these filters.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $records->links() }}</div></section>
@push('scripts')
<script>document.querySelectorAll('.hr-report-filter input[type=date]').forEach(input=>input.addEventListener('change',()=>{document.querySelector('.hr-report-filter select[name=range]').value='custom';}));</script>
@endpush
@endsection
