@extends('layouts.app')
@section('title',$staff->exists?'Edit staff':'Add staff')
@section('content')
<div class="page-heading"><div><span class="eyebrow">HUMAN RESOURCES</span><h1>{{ $staff->exists?'Edit staff':'Welcome a new team member' }}</h1><p>Staff records are independent of POS logins. A user account is optional.</p></div><a class="btn secondary" href="{{ route('hr.staff.index') }}">Back to staff</a></div>@include('hr.partials.nav')
<form action="{{ $staff->exists?route('hr.staff.update',$staff):route('hr.staff.store') }}" method="POST" class="hr-form-stack">@csrf @if($staff->exists)@method('PUT')@endif
<section class="card"><div class="card-heading"><div><h2>Personal & contact details</h2><p>Keep essentials ready for staff administration.</p></div><span class="tile-icon"><x-icon name="contact"/></span></div><div class="form-grid p-6">
@foreach(['name'=>'Full name','phone'=>'Phone','email'=>'Email','emergency_contact'=>'Emergency contact','emergency_phone'=>'Emergency phone'] as $key=>$label)<label class="field">{{ $label }}@if($key==='name') <b class="required">*</b>@endif<input name="{{ $key }}" type="{{ $key==='email'?'email':'text' }}" value="{{ old($key,$staff->$key) }}" @required($key==='name')></label>@endforeach<label class="field">Address<textarea name="address" rows="2">{{ old('address',$staff->address) }}</textarea></label></div></section>
<section class="card"><div class="card-heading"><div><h2>Employment & pay rates</h2><p>Rates are copied into payroll snapshots when payroll is prepared.</p></div><span class="tile-icon"><x-icon name="briefcase-business"/></span></div><div class="form-grid p-6">
@if($staff->status!=='EXITED')<label class="field">Staff record status<select name="status"><option value="ACTIVE" @selected(old('status',$staff->status)==='ACTIVE')>Active</option><option value="INACTIVE" @selected(old('status',$staff->status)==='INACTIVE')>Inactive</option></select><small>Use the staff profile to record an employment exit. Login access is managed separately below.</small></label>@endif
<label class="field">Intake date <b class="required">*</b><input type="date" name="joined_on" value="{{ old('joined_on',$staff->joined_on?->toDateString()) }}" max="{{ today()->toDateString() }}" required></label><label class="field">Employment type<select name="employment_type">@foreach(['PERMANENT'=>'Permanent','CONTRACT'=>'Contract','PART_TIME'=>'Part time','TEMPORARY'=>'Temporary'] as $k=>$v)<option value="{{ $k }}" @selected(old('employment_type',$staff->employment_type)===$k)>{{ $v }}</option>@endforeach</select></label>
@foreach(['department_id'=>['Department','department'],'position_id'=>['Job title','position'],'shift_id'=>['Shift','shift']] as $key=>[$label,$kind])<label class="field">{{ $label }}<select name="{{ $key }}"><option value="">Not assigned</option>@foreach($options->get($kind,collect()) as $o)<option value="{{ $o->id }}" @selected(old($key,$staff->$key)==$o->id)>{{ $o->name }}{{ $o->active?'':' (inactive)' }}</option>@endforeach</select></label>@endforeach
<label class="field">Salary basis<select name="salary_basis"><option value="MONTHLY" @selected(old('salary_basis',$staff->salary_basis)==='MONTHLY')>Monthly salary</option><option value="DAILY" @selected(old('salary_basis',$staff->salary_basis)==='DAILY')>Daily rate</option></select></label><label class="field">Salary / daily rate<input type="number" min="0" step="0.01" name="salary_rate" value="{{ old('salary_rate',$staff->salary_rate) }}" required></label><label class="field">Overtime rate / hour<input type="number" min="0" step="0.01" name="overtime_rate" value="{{ old('overtime_rate',$staff->overtime_rate) }}" required></label><label class="field">Bank / payment details<textarea name="bank_details" rows="2">{{ old('bank_details',$staff->bank_details) }}</textarea></label><label class="field">Notes<textarea name="notes" rows="2">{{ old('notes',$staff->notes) }}</textarea></label></div></section>
@can('hr.staff.accounts')@if(auth()->user()->hasPermission($staff->user_id?'users.edit':'users.create'))
<section class="card"><div class="card-heading"><div><h2>Optional system login</h2><p>Select a user role to create a login. Leave it unassigned for a staff record only.</p></div><span class="tile-icon"><x-icon name="shield-check"/></span></div><div class="form-grid p-6"><input type="hidden" name="account_present" value="1"><label class="field">User role<select name="role_id"><option value="">No system login</option>@foreach($roles as $r)<option value="{{ $r->id }}" @selected(old('role_id',$staff->user?->role_id)==$r->id)>{{ $r->name }}</option>@endforeach</select></label><label class="field">Username<input name="username" value="{{ old('username',$staff->user?->username) }}" autocapitalize="none" autocomplete="off" spellcheck="false"><small>Required when a role is selected.</small></label><label class="field">{{ $staff->user_id?'New password':'Password' }}<input type="password" name="password" minlength="10" maxlength="128" autocomplete="new-password"><small>{{ $staff->user_id?'Leave blank to keep the password.':'At least 10 characters for a new account.' }}</small></label><label class="field">Account email (optional)<input type="email" name="account_email" value="{{ old('account_email',$staff->user?->email) }}"><small>A private internal identifier is generated when no account email is entered.</small></label><label class="setting-tile"><input type="hidden" name="login_active" value="0"><input type="checkbox" name="login_active" value="1" @checked(old('login_active',$staff->user?->active??true))><span><strong>Login active</strong><small>Inactive accounts cannot sign in. Staff exits automatically deactivate access.</small></span></label></div></section>
@endif @endcan
<div class="form-footer"><a class="btn secondary" href="{{ route('hr.staff.index') }}">Cancel</a><button class="btn primary"><x-icon name="check"/>{{ $staff->exists?'Save staff':'Add staff member' }}</button></div></form>
@endsection
