@extends('layouts.app')
@section('title',$staff->name)
@section('content')
<div class="page-heading"><div><span class="eyebrow">STAFF PROFILE · {{ $staff->code }}</span><h1>{{ $staff->name }}</h1><p>{{ $staff->department?->name??'No department' }} · {{ $staff->position?->name??'No job title' }} · {{ ucfirst(strtolower($staff->status)) }}</p></div><div class="heading-actions">@can('hr.ledger.view')<a class="btn secondary" href="{{ route('hr.staff.ledger',$staff) }}"><x-icon name="book-open"/>Staff ledger</a>@endcan @can('hr.staff.edit')<a class="btn primary" href="{{ route('hr.staff.edit',$staff) }}"><x-icon name="pencil"/>Edit staff</a>@endcan</div></div>@include('hr.partials.nav')
@if($balances)<div class="stat-grid mb-6">@foreach(['salary_due'=>'Salary due','advances'=>'Outstanding advance','balance'=>'Company balance'] as $k=>$v)<div class="card stat-card"><div class="stat-top">{{ $v }}</div><strong>{{ $settings['currency_symbol']??'Rs.' }} {{ \App\Support\Money::display($balances[$k]) }}</strong></div>@endforeach</div>@endif
<div class="hr-profile-grid"><section class="card"><div class="card-heading"><h2>Staff details</h2><span class="badge {{ $staff->status==='ACTIVE'?'green':'slate' }}">{{ $staff->status }}</span></div><dl class="detail-grid p-6">@foreach(['phone'=>'Phone','email'=>'Email','address'=>'Address','emergency_contact'=>'Emergency contact','emergency_phone'=>'Emergency phone'] as $key=>$label)<div><dt>{{ $label }}</dt><dd>{{ $staff->$key??'—' }}</dd></div>@endforeach<div><dt>Intake date</dt><dd>{{ $staff->joined_on->format('d M Y') }}</dd></div><div><dt>Exit date</dt><dd>{{ $staff->left_on?->format('d M Y')??'—' }}</dd></div><div><dt>Shift</dt><dd>{{ $staff->shift?->name??'—' }}</dd></div><div><dt>System login</dt><dd>{{ $staff->user?->username??'No login' }} @if($staff->user)· {{ $staff->user->active?'Active':'Inactive' }} · {{ $staff->user->role?->name }}@endif</dd></div>@can('hr.payroll.view')<div><dt>Salary rate</dt><dd>{{ \App\Support\Money::display($staff->salary_rate) }} / {{ strtolower($staff->salary_basis) }}</dd></div><div><dt>Overtime / hour</dt><dd>{{ \App\Support\Money::display($staff->overtime_rate) }}</dd></div>@endcan</dl>@if($staff->notes)<p class="p-6 muted">{{ $staff->notes }}</p>@endif</section>
<section class="card"><div class="card-heading"><h2>Employment history</h2><x-icon name="history"/></div><div class="hr-timeline p-6">@foreach($events as $event)<div><span class="status-dot"></span><strong>{{ ucfirst(strtolower($event->type)) }}</strong><small>{{ $event->event_date->format('d M Y') }} · {{ $event->user->name }}</small>@if($event->reason)<p>{{ $event->reason }}</p>@endif</div>@endforeach</div>@can('hr.staff.exit')<details class="hr-details"><summary>{{ $staff->status==='EXITED'?'Record rehire':'Record staff exit' }}</summary><form method="POST" action="{{ route('hr.staff.employment',$staff) }}" class="hr-inline-form">@csrf<input type="hidden" name="type" value="{{ $staff->status==='EXITED'?'REHIRE':'EXIT' }}"><label class="field">Effective date<input type="date" name="date" value="{{ today()->toDateString() }}" max="{{ today()->toDateString() }}" required></label><label class="field">Reason<textarea name="reason" required></textarea></label><p class="muted">Employment and payment history remain available. Exiting staff deactivates their linked login.</p><button class="btn {{ $staff->status==='EXITED'?'primary':'danger' }}">{{ $staff->status==='EXITED'?'Record rehire':'Confirm staff exit' }}</button></form></details>@endcan</section></div>
@can('hr.payroll.view')<section class="card mt-6"><div class="card-heading"><h2>Payroll history</h2></div><div class="table-wrap"><table><thead><tr><th>Payroll</th><th>Month</th><th>Net salary</th><th>Due</th><th>Status</th></tr></thead><tbody>@forelse($payrolls as $p)<tr><td><a class="text-link" href="{{ route('hr.payroll.show',$p) }}">{{ $p->reference }}</a></td><td>{{ $p->period->format('F Y') }}</td><td>{{ \App\Support\Money::display($p->net) }}</td><td>{{ $p->status==='VOIDED'?'—':\App\Support\Money::display($p->due) }}</td><td><span class="badge {{ $p->status==='APPROVED'?'green':'slate' }}">{{ $p->status }}</span></td></tr>@empty<tr><td class="empty-cell" colspan="5">No payroll records yet.</td></tr>@endforelse</tbody></table></div></section>@endcan
@endsection
