@extends('layouts.app')
@section('title',$record->name)
@section('content')
<div class="page-heading"><div><span class="eyebrow">PRODUCT DETAILS</span><h1>{{ $record->name }}</h1><p>{{ $record->sku }} · {{ $record->categories->pluck('name')->join(', ') }}</p></div><div class="heading-actions"><a class="btn secondary" href="{{ route('manage.index','products') }}">Products</a>@can('products.edit')<a class="btn primary" href="{{ route('manage.edit',['products',$record->id]) }}"><x-icon name="pencil"/>Edit product</a>@endcan</div></div>
<div class="product-profile"><aside class="card product-image-card"><div class="product-image-preview">@if($record->image)<img src="{{ asset('storage/'.$record->image) }}" alt="{{ $record->name }}">@else<x-icon name="package" :size="48"/>@endif</div><span class="badge {{ $record->active?'green':'slate' }}">{{ $record->active?'Active':'Inactive' }}</span><dl class="detail-grid"><div><dt>Barcode</dt><dd>{{ $record->barcode??'—' }}</dd></div>@can('products.view_cost')<div><dt>Default cost / {{ $record->unit->short_name }}</dt><dd>{{ $settings['currency_symbol']??'Rs.' }} {{ \App\Support\Money::display($record->cost) }}</dd></div>@endcan<div><dt>Current stock</dt><dd>{{ (float)$record->stock }} {{ $record->unit->short_name }}</dd></div><div><dt>Low stock alert</dt><dd>{{ (float)$record->low_stock }} {{ $record->unit->short_name }}</dd></div></dl><a class="btn secondary" href="#stock-history"><x-icon name="history"/>Stock movement history</a></aside>
<section class="card product-unit-details"><div class="customer-section-heading"><span class="customer-section-icon"><x-icon name="ruler"/></span><div><h2>Units & prices</h2><p>One stock balance, multiple ways to sell.</p></div></div><div class="table-wrap"><table><thead><tr><th>Unit</th><th>Conversion</th><th>Selling price / unit</th></tr></thead><tbody>@php($priceGroups=app(\App\Services\StockLayerService::class)->groups($record)) @foreach(app(\App\Services\ProductUnitService::class)->options($record) as $unit)<tr><td><strong>{{ $unit['name'] }}</strong> ({{ $unit['short_name'] }}) @if($unit['id']==$record->unit_id)<span class="badge green">Primary</span>@endif</td><td>{{ (float)$unit['base_quantity'] }} {{ $record->unit->short_name }} = {{ (float)$unit['converted_quantity'] }} {{ $unit['short_name'] }}</td><td>{{ $settings['currency_symbol']??'Rs.' }} @php($unitPrices=collect($priceGroups)->flatMap(fn($g)=>$g['units'])->where('id',$unit['id'])->pluck('price')->unique()->sort()->values()) @if($unitPrices->isNotEmpty()){{ \App\Support\Money::display($unitPrices->first()) }}@if($unitPrices->count()>1) – {{ \App\Support\Money::display($unitPrices->last()) }}@endif @else{{ \App\Support\Money::display($unit['price']) }} <small class="muted">default · no available stock</small>@endif</td></tr>@endforeach</tbody></table></div><div class="conversion-note"><x-icon name="info" :size="16"/>All stock movements use {{ $record->unit->name }} ({{ $record->unit->short_name }}).</div></section></div>
@include('products.partials.stock-prices')
@include('products.partials.stock-history',['product'=>$record])
@endsection
