<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $sale->invoice }} · Receipt</title><style>
*{box-sizing:border-box}body{margin:0;background:#f1f5f9;color:#111;font:12px/1.4 Arial,sans-serif}.receipt{width:{{ $settings['paper_width']??80 }}mm;margin:24px auto;background:white;padding:4mm}.center{text-align:center}.logo{max-width:36mm;max-height:22mm;object-fit:contain;margin-bottom:3mm}h1{font-size:17px;margin:0 0 2mm}p{margin:1mm 0;overflow-wrap:anywhere}.rule{border-top:1px dashed #111;margin:3mm 0}.meta{font-size:11px}.row{display:flex;justify-content:space-between;gap:2mm;margin:1.5mm 0}.row span{overflow-wrap:anywhere}.row strong{white-space:nowrap}.grand{font-size:15px;font-weight:bold;border-top:1px dashed #111;padding-top:2mm}table{width:100%;border-collapse:collapse;table-layout:fixed}th{border-bottom:1px dashed #111;font-size:11px;text-align:left;padding:1mm 0}td{vertical-align:top;padding:2mm 0;overflow-wrap:anywhere}th:first-child{width:48%}th:nth-child(2){width:22%}th:last-child{width:30%;text-align:right}td:last-child{text-align:right;white-space:nowrap}small{display:block;font-size:10px}.controls{display:flex;justify-content:center;gap:12px;padding:18px}button,a.control{border:0;border-radius:8px;padding:10px 18px;background:#047857;color:white;text-decoration:none;cursor:pointer}.void{border:2px solid black;font-weight:bold;padding:2mm;text-align:center}.footer{white-space:pre-line}tr{break-inside:avoid}@page{size:{{ $settings['paper_width']??80 }}mm 297mm;margin:0}@media print{body{background:white}.receipt{margin:0;padding:3mm;width:{{ $settings['paper_width']??80 }}mm}.controls{display:none}} </style><style id="receipt-page-size"></style></head><body><div class="controls" @if(request('embed'))style="display:none"@endif><button onclick="window.print()">Print receipt</button>@can('sales.view')<a class="control" href="{{ route('sales.show',$sale) }}">Sale details</a>@endcan<a class="control" href="{{ route('pos.index') }}">Back to POS</a></div><main class="receipt">
@if($sale->status==='VOIDED')<div class="void">VOIDED INVOICE</div>@endif<div class="center">@if(($settings['show_logo_receipt']??true) && !empty($settings['logo']))<img class="logo" src="{{ asset('storage/'.$settings['logo']) }}" alt="Business logo">@endif<h1>{{ $settings['business_name']??'' }}</h1>@if(!empty($settings['legal_name']))<p>{{ $settings['legal_name'] }}</p>@endif<p>{{ $settings['address']??'' }}</p>@if(!empty($settings['city']))<p>{{ $settings['city'] }}</p>@endif<p>{{ $settings['phone']??'' }} {{ $settings['mobile']??'' }}</p>@if(!empty($settings['tax_number']))<p>Tax / VAT: {{ $settings['tax_number'] }}</p>@endif</div><div class="rule"></div><div class="meta"><p>Invoice: {{ $sale->invoice }}</p><p>Date: {{ $sale->sold_at->format(($settings['date_format']??'d/m/Y').' '.($settings['time_format']??'h:i A')) }}</p>@if($settings['show_cashier']??true)<p>Cashier: {{ $sale->user->name }}</p>@endif @if(($settings['show_customer']??true) && $sale->customer)<p>Customer: {{ $sale->customer->name }}</p>@endif</div><div class="rule"></div><table><thead><tr><th>Item</th><th>Qty</th><th>Amount</th></tr></thead><tbody>@foreach($sale->items as $item)<tr><td>{{ $item->name }}@if($settings['show_sku']??false)<small>{{ $item->sku }}</small>@endif<small>{{ \App\Support\Money::display(\App\Support\Money::compare($item->line_discount??0,0)>0?app(\App\Services\ProductUnitService::class)->rate($item->total,'1',$item->quantity):$item->price) }} @if($settings['show_unit']??true)/ {{ $item->unit }}@endif</small></td><td>{{ rtrim(rtrim($item->quantity,'0'),'.') }}@if($settings['show_unit']??true) {{ $item->unit }} @endif</td><td>{{ \App\Support\Money::display($item->total) }}</td></tr>@endforeach</tbody></table><div class="rule"></div><div class="row"><span>Subtotal</span><strong>{{ \App\Support\Money::display(\App\Support\Money::sub($sale->subtotal,$sale->line_discount_total)) }}</strong></div>@if(\App\Support\Money::compare(\App\Support\Money::sub($sale->discount,$sale->line_discount_total),0)>0)<div class="row"><span>Discount</span><strong>-{{ \App\Support\Money::display(\App\Support\Money::sub($sale->discount,$sale->line_discount_total)) }}</strong></div>@endif<div class="row"><span>Sale total</span><strong>{{ \App\Support\Money::display($sale->sale_amount) }}</strong></div>
@if($settings['show_payment_method']??true)<p>Payment: {{ $sale->payment_names ?: 'On account (unpaid)' }}</p>@endif
@foreach($sale->payments as $payment)
@if(\App\Support\Money::compare($payment->processing_charge,0)>0)
@if($payment->charge_bearer==='CUSTOMER')<div class="row"><span>{{ ($settings['show_surcharge']??true)?$payment->method_name.' Processing Fee':'Payment processing fee' }} @if(($settings['show_surcharge']??true) && $payment->charge_type==='PERCENTAGE')({{ rtrim(rtrim($payment->charge_value,'0'),'.') }}%)@endif</span><strong>{{ \App\Support\Money::display($payment->processing_charge) }}</strong></div>
@else<p>{{ $payment->method_name }} processing fee: paid by merchant</p>@if($settings['show_merchant_fee']??false)<div class="row"><span>Merchant fee</span><strong>{{ \App\Support\Money::display($payment->processing_charge) }}</strong></div>@endif @endif @endif
@endforeach
<div class="row grand"><span>GRAND TOTAL</span><strong>{{ $settings['currency_symbol']??'Rs.' }} {{ \App\Support\Money::display($sale->customer_payable) }}</strong></div>
@if($sale->payments->count()>1)@foreach($sale->payments as $payment)<div class="row"><span>{{ ($settings['show_payment_method']??true)?$payment->method_name:'Payment '.$loop->iteration }}</span><strong>{{ \App\Support\Money::display($payment->customer_payable) }}</strong></div>@endforeach<div class="rule"></div>@endif
<div class="row"><span>Paid</span><strong>{{ \App\Support\Money::display($sale->paid_total) }}</strong></div>@if($sale->payments->contains('method_type','CASH'))<div class="row"><span>Change</span><strong>{{ \App\Support\Money::display($sale->change_total) }}</strong></div>@endif
@if($sale->returns->isNotEmpty())<div class="rule"></div><div class="row"><span>Items returned</span><strong>-{{ \App\Support\Money::display($sale->returned_total) }}</strong></div><div class="row"><span>Refunds paid</span><strong>{{ \App\Support\Money::display($sale->refunded_total) }}</strong></div>@endif
@if(\App\Support\Money::compare($sale->due_balance,0)>0)<div class="row grand"><span>BALANCE DUE</span><strong>{{ \App\Support\Money::display($sale->due_balance) }}</strong></div>@endif
<div class="rule"></div><div class="center footer">{{ $settings['receipt_message']??'' }}</div><p class="center footer">{{ $settings['receipt_footer']??'' }}</p><div class="rule"></div><p class="center">{{ $sale->invoice }}</p></main><script>
function sizeReceiptPage(){const height=Math.max(80,Math.ceil(document.querySelector('.receipt').getBoundingClientRect().height*25.4/96)+4);document.getElementById('receipt-page-size').textContent='@page{size:{{ $settings['paper_width']??80 }}mm '+height+'mm;margin:0}';}
window.addEventListener('load',sizeReceiptPage);window.addEventListener('beforeprint',sizeReceiptPage);
</script>@if(request('print'))<script>window.addEventListener('load',()=>window.print());</script>@endif</body></html>
