@extends('layouts.app')
@section('title', 'Sale details')
@section('content')
@php
    $currency = $settings['currency_symbol'] ?? 'Rs.';
    $itemsRemaining = collect($returnable)->contains(fn($line)=>\App\Support\Money::compare($line['remaining'],0)>0);
    $openAction = old('_action', request('action'));
@endphp
<div class="page-heading sale-heading"><div><a class="text-link" href="{{ route('sales.index') }}"><x-icon name="arrow-left" :size="16"/>All sales</a><span class="eyebrow">INVOICE DETAILS</span><h1>{{ $sale->invoice }} <span class="badge {{ $sale->payment_status==='Due'?'amber':($sale->status==='ACTIVE'?'green':'red') }}">{{ $sale->payment_status }}</span></h1><p>{{ $sale->sold_at->format(($settings['date_format']??'d/m/Y').' '.($settings['time_format']??'h:i A')) }} · {{ $sale->user->name }} · REG-{{ $sale->register_id }}</p></div>@can('sales.receipt')<a class="btn secondary" href="{{ route('sales.receipt', $sale) }}" target="_blank"><x-icon name="printer"/>Print receipt</a>@endcan</div>
@if($sale->status==='VOIDED')<div class="notice error">Reversed by {{ $sale->voider?->name }} on {{ $sale->voided_at?->format('d/m/Y H:i') }}: {{ $sale->void_reason }}</div>@endif
<section class="card sale-hero"><div class="sale-customer"><span class="avatar"><x-icon name="contact" :size="24"/></span><div><span class="eyebrow">CUSTOMER</span><h2>{{ $sale->customer?->name ?? 'Walk-in customer' }}</h2><p>{{ $sale->customer?->phone ?? 'Counter sale' }}@if($sale->customer?->email) · {{ $sale->customer->email }}@endif</p></div></div>@include('sales.partials.actions', ['showView'=>false])</section>
<div class="sale-metrics">
    @foreach(['Invoice total'=>$sale->customer_payable,'Collected'=>$sale->collected_total,'Returned'=>$sale->returned_total,'Balance due'=>$sale->due_balance] as $label=>$value)<div class="card {{ $label==='Balance due'?'sale-due-metric':'' }}"><span>{{ $label }}</span><strong>{{ $currency }} {{ \App\Support\Money::display($value) }}</strong>@if($label==='Collected')<small>After cash change · before refunds</small>@elseif($label==='Returned')<small>Refunded {{ $currency }} {{ \App\Support\Money::display($sale->refunded_total) }}</small>@endif</div>@endforeach
</div>
<div class="sale-detail-layout">
    <div class="sale-main-column">
        <section class="card"><div class="card-heading"><div><h2>Items purchased</h2><p>{{ $sale->items->count() }} {{ Str::plural('item', $sale->items->count()) }}</p></div><x-icon name="shopping-bag" class="muted"/></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Quantity</th><th class="text-right">Unit price</th><th class="text-right">Line total</th></tr></thead><tbody>
        @foreach($returnable as $line)@php($item=$line['item'])<tr><td><strong>{{ $item->name }}</strong><small class="cell-note">{{ $item->sku }}@if(\App\Support\Money::compare($line['returned'],0)>0) · Returned {{ rtrim(rtrim($line['returned'],'0'),'.') }} {{ $item->unit }}@endif</small></td><td>{{ rtrim(rtrim($item->quantity,'0'),'.') }} {{ $item->unit }}</td><td class="text-right">{{ \App\Support\Money::display($item->price) }}</td><td class="text-right"><strong>{{ \App\Support\Money::display($item->total) }}</strong>@if(\App\Support\Money::compare($item->line_discount??0,0)>0)<small class="cell-note">Line discount {{ \App\Support\Money::display($item->line_discount) }}</small>@endif</td></tr>@endforeach
        </tbody></table></div></section>
        <section class="card mt-6"><div class="card-heading"><div><h2>Payment history</h2><p>Recorded tenders and later due collections</p></div><x-icon name="wallet" class="muted"/></div><div class="sale-payment-list">
        @forelse($sale->payments as $payment)<article><span class="stat-icon green"><x-icon :name="match($payment->method_type){'CASH'=>'banknote','CARD'=>'credit-card','QR'=>'qr-code',default=>'landmark'}"/></span><div class="sale-payment-copy"><h3>{{ $payment->method_name }} <span class="badge slate">Recorded payment</span></h3><p>Received {{ $currency }} {{ \App\Support\Money::display($payment->amount_paid) }} · Change {{ \App\Support\Money::display($payment->change) }}</p>@if($payment->reference)<p>Reference: {{ $payment->reference }}</p>@endif<details><summary>Processing details</summary><dl class="detail-grid"><div><dt>Allocated sale amount</dt><dd>{{ \App\Support\Money::display($payment->sale_amount) }}</dd></div><div><dt>Required collection</dt><dd>{{ \App\Support\Money::display($payment->customer_payable) }}</dd></div><div><dt>Fee / payer</dt><dd>{{ \App\Support\Money::display($payment->processing_charge) }} · {{ ucfirst(strtolower($payment->charge_bearer)) }}</dd></div><div><dt>Rule / expense</dt><dd>{{ $payment->rule_name ?? 'No charge rule' }}{{ $payment->expense?' · EXP-'.$payment->expense->id.' '.$payment->expense->status:'' }}</dd></div></dl></details></div><strong>{{ $currency }} {{ \App\Support\Money::display(\App\Support\Money::sub($payment->amount_paid,$payment->change)) }}</strong></article>@empty<p class="padded muted">No payment received yet.</p>@endforelse
        @foreach($sale->collections as $payment)<article><span class="stat-icon green"><x-icon name="wallet"/></span><div class="sale-payment-copy"><h3>{{ $payment->method_name }} <span class="badge green">Due payment</span></h3><p>{{ $payment->collected_at->format('d/m/Y h:i A') }} · {{ $payment->user->name }} · REG-{{ $payment->register_id }}</p><p>Received {{ \App\Support\Money::display($payment->amount_paid) }} · Change {{ \App\Support\Money::display($payment->change) }}@if($payment->reference) · {{ $payment->reference }}@endif</p></div><strong>{{ $currency }} {{ \App\Support\Money::display($payment->amount) }}</strong></article>@endforeach
        </div></section>
        @if($sale->returns->isNotEmpty())<section class="card mt-6"><div class="card-heading"><div><h2>Returns &amp; refunds</h2><p>Stock and payments recorded in the return's register</p></div></div><div class="sale-payment-list">@foreach($sale->returns as $return)<article><span class="stat-icon amber"><x-icon name="package-open"/></span><div class="sale-payment-copy"><h3>{{ $return->reference }}</h3><p>{{ $return->returned_at->format('d/m/Y h:i A') }} · {{ $return->user->name }} · REG-{{ $return->register_id }}</p><p>{{ $return->reason }}</p>@foreach($return->items as $line)<p>{{ $line->item->name }} · {{ rtrim(rtrim($line->quantity,'0'),'.') }} {{ $line->item->unit }}</p>@endforeach<p>Due reduced {{ \App\Support\Money::display($return->due_reduction) }} · Refunded {{ \App\Support\Money::display($return->refund_amount) }} {{ $return->method_name }}</p></div><strong>−{{ $currency }} {{ \App\Support\Money::display($return->amount) }}</strong></article>@endforeach</div></section>@endif
        @if($sale->notes)<section class="card padded mt-6"><h2>Order notes</h2><p class="sale-notes">{{ $sale->notes }}</p></section>@endif
    </div>
    <aside class="card padded sale-summary"><span class="eyebrow">ORDER SUMMARY</span><h2>Invoice breakdown</h2><div class="summary-lines"><div><span>Subtotal</span><strong>{{ \App\Support\Money::display($sale->subtotal) }}</strong></div><div><span>Discounts</span><strong>−{{ \App\Support\Money::display($sale->discount) }}</strong></div><div><span>Sale amount</span><strong>{{ \App\Support\Money::display($sale->sale_amount) }}</strong></div><div><span>Customer fees</span><strong>{{ \App\Support\Money::display($sale->customer_fees) }}</strong></div><div class="grand"><span>Invoice total</span><strong>{{ $currency }} {{ \App\Support\Money::display($sale->customer_payable) }}</strong></div><div><span>Returns</span><strong>−{{ \App\Support\Money::display($sale->returned_total) }}</strong></div><div><span>Net payable</span><strong>{{ \App\Support\Money::display(\App\Support\Money::sub($sale->customer_payable,$sale->returned_total)) }}</strong></div><div><span>Collected less refunds</span><strong>{{ \App\Support\Money::display(\App\Support\Money::sub($sale->collected_total,$sale->refunded_total)) }}</strong></div><div class="sale-balance"><span>Balance due</span><strong>{{ $currency }} {{ \App\Support\Money::display($sale->due_balance) }}</strong></div></div>
    @if($sale->status==='ACTIVE' && \App\Support\Money::compare($sale->due_balance,0)>0)@can('sales.collect_payment')<a class="btn primary w-full" href="{{ route('sales.show', [$sale,'action'=>'pay']) }}"><x-icon name="wallet"/>Pay due</a>@endcan @else<p class="sale-settled"><x-icon name="circle-check" :size="18"/>{{ $sale->status==='ACTIVE'?'Payment settled':'Invoice reversed' }}</p>@endif
    @if($sale->register->closed_at)<p class="muted text-xs">Original register closed. Returns and due payments use your current open register.</p>@endif
    </aside>
</div>
@include('sales.partials.dialogs')
@endsection
@push('scripts')@vite('resources/js/sales.js')@endpush
