@extends('layouts.app')
@section('title','Suppliers')
@section('content')
@php($currency=$settings['currency_symbol']??'Rs.')
<div class="page-heading"><div><span class="eyebrow">SUPPLIER ACCOUNTS</span><h1>Suppliers</h1><p>Contacts, purchase history and outstanding balances in one place.</p></div>@can('suppliers.create')<a class="btn primary" href="{{ route('manage.create','suppliers') }}"><x-icon name="plus"/>Add supplier</a>@endcan
</div>
<div class="account-overview"><div class="card account-stat"><span class="tile-icon"><x-icon name="truck"/></span><div><span>Suppliers</span><strong>{{ $stats->total??0 }}</strong></div></div><div class="card account-stat"><span class="tile-icon"><x-icon name="wallet"/></span><div><span>Confirmed outstanding due</span><strong>{{ $currency }} {{ \App\Support\Money::display($stats->total_due??0) }}</strong></div></div><div class="card account-stat"><span class="tile-icon"><x-icon name="file-text"/></span><div><span>Purchases awaiting payment balances</span><strong>{{ $stats->unrecorded_count??0 }}</strong></div></div></div>
<section class="card"><form class="filter-bar" method="GET"><label class="search-field"><x-icon name="search"/><input type="search" name="q" value="{{ request('q') }}" placeholder="Search supplier or phone…" aria-label="Search suppliers"></label><select name="active" aria-label="Supplier status"><option value="">All statuses</option><option value="1" @selected(request('active')==='1')>Active</option><option value="0" @selected(request('active')==='0')>Inactive</option></select><button class="btn secondary">Apply</button><a class="text-link" href="{{ route('manage.index','suppliers') }}">Reset</a></form><div class="table-wrap"><table><thead><tr><th>Supplier</th><th>Contact</th><th>Outstanding due</th><th>Status</th><th class="text-right">Actions</th></tr></thead><tbody>@forelse($rows as $supplier)<tr><td><a class="text-link" href="{{ route('manage.show',['suppliers',$supplier->id]) }}">{{ $supplier->name }}</a><small class="table-secondary">SUP-{{ str_pad($supplier->id,5,'0',STR_PAD_LEFT) }}</small></td><td>{{ $supplier->phone??'No phone added' }}<small class="table-secondary">{{ $supplier->email??'No email added' }}</small></td><td><strong class="{{ \App\Support\Money::compare($supplier->due_balance,0)>0?'text-warning':'' }}">{{ $currency }} {{ \App\Support\Money::display($supplier->due_balance) }}</strong>@if($supplier->unrecorded_count)<small class="table-secondary">{{ $supplier->unrecorded_count }} purchase balances not recorded</small>@endif
</td><td><span class="badge {{ $supplier->active?'green':'slate' }}">{{ $supplier->active?'Active':'Inactive' }}</span></td><td><div class="row-actions"><a class="btn secondary small" href="{{ route('manage.show',['suppliers',$supplier->id]) }}"><x-icon name="eye" :size="16"/>View</a>@can('suppliers.edit')<a class="btn secondary small" href="{{ route('manage.edit',['suppliers',$supplier->id]) }}"><x-icon name="pencil" :size="16"/>Edit</a>@endcan @can('suppliers.delete')<form method="POST" action="{{ route('manage.destroy',['suppliers',$supplier->id]) }}" data-confirm="Delete this supplier? Suppliers with purchase history cannot be deleted.">@csrf @method('DELETE')<button class="icon-button text-danger" aria-label="Delete {{ $supplier->name }}"><x-icon name="trash-2" :size="17"/></button></form>@endcan
</div></td></tr>@empty
<tr><td colspan="5" class="empty-cell">No suppliers match these filters.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $rows->links() }}</div></section>
@endsection
