@extends('layouts.app')
@section('title','Supplier account')
@section('content')
@php($currency=$settings['currency_symbol']??'Rs.')
<div class="page-heading"><div><span class="eyebrow">SUPPLIER ACCOUNT</span><h1>{{ $record->name }}</h1><p>Purchase invoices, payments, refunds and a running ledger.</p></div><div class="heading-actions"><a class="btn secondary" href="{{ route('manage.index','suppliers') }}"><x-icon name="arrow-left"/>Suppliers</a>@can('purchases.edit')<a class="btn primary" href="{{ route('manage.edit',['suppliers',$record->id]) }}"><x-icon name="pencil"/>Edit supplier</a>@endcan
</div></div>
<div class="supplier-profile"><section class="card supplier-contact"><span class="tile-icon"><x-icon name="truck"/></span><div><strong>{{ $record->name }}</strong><p>{{ $record->address??'No address added' }}</p><span>{{ $record->phone??'No phone added' }} @if($record->email) · {{ $record->email }}@endif
</span></div><span class="badge {{ $record->active?'green':'slate' }}">{{ $record->active?'Active':'Inactive' }}</span></section><section class="card supplier-due"><span class="eyebrow">CURRENT OUTSTANDING DUE</span><strong>{{ $currency }} {{ \App\Support\Money::display($record->due_balance) }}</strong><small>Across active purchases with recorded payment balances.</small>@if($record->unrecorded_count)<p class="text-warning">{{ $record->unrecorded_count }} purchase balances still need to be recorded.</p>@endif
</section></div>
<section class="card account-filters"><div class="card-heading"><div><h2>Account history</h2><p class="muted">Choose a date range for the history and downloads.</p></div><div class="heading-actions"><a class="btn primary" href="{{ route('manage.suppliers.ledger',['supplier'=>$record->id]+$filters+['export'=>'pdf']) }}"><x-icon name="download"/>Download ledger PDF</a><a class="btn secondary" href="{{ route('manage.suppliers.ledger',['supplier'=>$record->id]+$filters+['export'=>'csv']) }}"><x-icon name="download"/>CSV</a></div></div><form method="GET" class="filter-bar"><label class="field compact">From<input type="date" name="from" value="{{ $filters['from']??'' }}"></label><label class="field compact">To<input type="date" name="to" value="{{ $filters['to']??'' }}"></label><button class="btn secondary">Apply filters</button><a class="text-link" href="{{ route('manage.show',['suppliers',$record->id]) }}">All history</a></form></section>
<div class="account-overview ledger-summary">@foreach(['opening'=>'Opening balance','debits'=>'Period debits','credits'=>'Period credits','closing'=>'Closing balance'] as $key=>$label)<div class="card account-stat"><div><span>{{ $label }}</span><strong>{{ $currency }} {{ \App\Support\Money::display($account[$key]) }}</strong></div></div>@endforeach
</div>
<section class="card mb-6"><div class="card-heading"><div><h2>Purchase history</h2><p class="muted">{{ $purchases->total() }} invoices in this period</p></div></div><div class="table-wrap"><table><thead><tr><th>Purchase / date</th><th>Total</th><th>Paid</th><th>Due</th><th>Status</th><th class="text-right">Actions</th></tr></thead><tbody>@forelse($purchases as $purchase)<tr><td><a class="text-link" href="{{ route('purchases.show',$purchase) }}">{{ $purchase->reference }}</a><small class="table-secondary">{{ $purchase->purchase_date->format('d M Y') }} · {{ $purchase->user?->name }}</small></td><td>{{ $currency }} {{ \App\Support\Money::display($purchase->total) }}</td><td>{{ $purchase->payment_tracking?$currency.' '.\App\Support\Money::display($purchase->paid_amount):'Not recorded' }}</td><td>{{ $purchase->due_amount!==null?$currency.' '.\App\Support\Money::display($purchase->due_amount):'Unknown' }}</td><td><span class="badge {{ $purchase->payment_status==='Paid'?'green':'slate' }}">{{ $purchase->payment_status }}</span></td><td><div class="row-actions"><a class="btn secondary small" href="{{ route('purchases.show',$purchase) }}"><x-icon name="eye" :size="16"/>View</a>@can('purchases.edit')@if($purchase->status==='ACTIVE' && $purchase->due_amount!==null && \App\Support\Money::compare($purchase->due_amount,0)>0)<a class="btn primary small" href="{{ route('purchases.show',['purchase'=>$purchase,'payment'=>1]) }}"><x-icon name="wallet" :size="16"/>Pay due</a>@endif @endcan
</div></td></tr>@empty
<tr><td colspan="6" class="empty-cell">No purchases in this period.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $purchases->links() }}</div></section>
<section class="card"><div class="card-heading"><div><h2>Supplier ledger</h2><p class="muted">{{ $ledger->total() }} entries · Debit increases the balance owed; credit reduces it.</p></div></div><div class="table-wrap"><table class="ledger-table"><thead><tr><th>Date / type</th><th>Purchase</th><th>Details</th><th class="text-right">Debit</th><th class="text-right">Credit</th><th class="text-right">Running balance</th></tr></thead><tbody>@forelse($ledger as $entry)<tr><td>{{ $entry['date']->format('d M Y, H:i') }}<small class="table-secondary">{{ $entry['type'] }}</small></td><td><a class="text-link" href="{{ route('purchases.show',$entry['purchase_id']) }}">{{ $entry['reference'] }}</a></td><td>{{ $entry['description'] }}@if($entry['type']==='Unrecorded')<small class="table-secondary">Invoice total: {{ $currency }} {{ \App\Support\Money::display($entry['amount']) }} · excluded from balance</small>@endif
</td><td class="text-right">{{ \App\Support\Money::display($entry['debit']) }}</td><td class="text-right">{{ \App\Support\Money::display($entry['credit']) }}</td><td class="text-right"><strong>{{ \App\Support\Money::display($entry['balance']) }}</strong></td></tr>@empty
<tr><td colspan="6" class="empty-cell">No ledger activity in this period.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $ledger->links() }}</div><p class="p-6 muted text-sm">The opening balance includes earlier activity. Unrecorded purchase payment balances are excluded until recorded. Opening payments represent previously paid amounts.</p></section>
@endsection
