@extends('layouts.app')
@section('title',ucfirst($group).' settings')
@section('content')<div class="page-heading"><div><span class="eyebrow">SETTINGS</span><h1>{{ ucfirst($group) }} settings</h1><p>Changes apply throughout your store.</p></div><a class="btn secondary" href="{{ route('settings.index') }}"><x-icon name="arrow-left"/>All settings</a></div>
@if($group==='stock')<div class="notice info"><x-icon name="info"/><span>Selling at zero stock also requires negative stock to be enabled when the sale will take stock below zero.</span></div>@endif
<form class="card form-card wide" method="POST" enctype="multipart/form-data" action="{{ route('settings.update',$group) }}">@csrf @method('PUT')<div class="form-grid">
@foreach($fields as $key=>$f)@php([$label,$type,$default]=$f)@php($value=old($key,$values[$key]??$default))
@if($type==='checkbox')<label class="check-card"><input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked($value)><span>{{ $label }}</span></label>
@elseif($type==='file')<div class="field"><span>{{ $label }}</span><input type="file" id="logo-upload" name="logo" accept="image/png,image/jpeg,image/webp" class="sr-only" aria-label="{{ $label }}" onchange="document.getElementById('remove-logo-flag').value='0';document.getElementById('logo-filename').textContent=this.files[0]?this.files[0].name:'No file selected'"><input type="hidden" name="remove_logo" id="remove-logo-flag" value="0"><button type="button" class="btn secondary w-fit" onclick="document.getElementById('logo-upload').click()">Change logo</button><small id="logo-filename">Select a file, then save your changes.</small>@if(!empty($values['logo']))<img id="current-logo" class="image-preview" src="{{ asset('storage/'.$values['logo']) }}" alt="Current business logo"><button type="button" class="btn danger w-fit" onclick="document.getElementById('remove-logo-flag').value='1';document.getElementById('logo-upload').value='';document.getElementById('current-logo').style.display='none';this.textContent='Logo will be removed on save'">Remove logo</button>@endif @error($key)<small class="text-danger">{{ $message }}</small>@enderror</div>
@else<label class="field {{ $type==='textarea'?'full':'' }}">{{ $label }}
@if($type==='textarea')<textarea name="{{ $key }}" rows="3">{{ $value }}</textarea>
@elseif(in_array($type,['payment','customer','choice','timezone']))<select name="{{ $key }}">@if($type==='customer')<option value="">Walk-in customer</option>@endif
@php($choices=match($type){'payment'=>$paymentMethods->pluck('name','id'),'customer'=>$customers->pluck('name','id'),'timezone'=>array_combine(timezone_identifiers_list(),timezone_identifiers_list()),default=>match($key){'return_default_stock_action'=>['RESTOCK'=>'Restock','WRITEOFF'=>'Write off / expense','SUPPLIER'=>'Return to supplier'],'return_fee_policy'=>['NONE'=>'Non-refundable','FULL'=>'Full refund on first return','PRO_RATA'=>'Pro-rata refund'],'search_mode'=>['all'=>'Name, barcode and SKU','name'=>'Name','barcode'=>'Barcode','sku'=>'SKU'],'paper_width'=>['80'=>'80mm thermal printer','58'=>'58mm thermal printer'],'date_format'=>['d/m/Y'=>'Day / Month / Year','Y-m-d'=>'Year - Month - Day','m/d/Y'=>'Month / Day / Year'],'time_format'=>['h:i A'=>'12 hour (09:35 PM)','H:i'=>'24 hour (21:35)']}})
@foreach($choices as $id=>$name)<option value="{{ $id }}" @selected((string)$value===(string)$id)>{{ $name }}</option>@endforeach</select>
@else<input name="{{ $key }}" type="{{ $type }}" @if($type!=='file')value="{{ $value }}"@else accept="image/png,image/jpeg,image/webp"@endif @if($type==='number')step="{{ in_array($key,['max_discount_percent','return_approval_above'])?'0.01':'1' }}" min="0"@endif @required(str_starts_with($f[3],'required'))>@endif
@error($key)<small class="text-danger">{{ $message }}</small>@enderror
</label>@endif @endforeach
</div><div class="form-footer"><a class="btn secondary" href="{{ route('settings.index') }}">Cancel</a><button class="btn primary"><x-icon name="check"/>Save changes</button></div></form>@endsection
