@extends('layouts.app')
@section('title','Roles & permissions')
@section('content')
<div class="page-heading"><div><span class="eyebrow">TEAM ACCESS</span><h1>Roles & permissions</h1><p>Give each team member the tools and information they need.</p></div>@can('roles.create')<a class="btn primary" href="{{ route('manage.create','roles') }}"><x-icon name="plus"/>Add role</a>@endcan</div>
<div class="role-overview"><div class="card role-overview-card"><span class="stat-icon green"><x-icon name="shield-check"/></span><div><strong>{{ $rows->total() }}</strong><span>Team roles</span></div></div><div class="card role-overview-card"><span class="stat-icon blue"><x-icon name="sliders-horizontal"/></span><div><strong>{{ count(\App\Support\Permissions::visible()) }}</strong><span>Individual permissions</span></div></div><div class="card role-admin-note"><x-icon name="shield-check"/><div><strong>Administrator always has full access</strong><p>Every current and future permission is included automatically.</p></div></div></div>
<section class="card roles-table-card"><div class="card-heading"><div><h2>Manage team access</h2><p>Dashboard cards, records, payments and reports are controlled separately.</p></div></div><form class="filter-bar" method="GET"><label class="search-field"><x-icon name="search"/><input name="q" value="{{ request('q') }}" placeholder="Search roles…" aria-label="Search roles"></label><button class="btn secondary">Search</button>@if(request('q'))<a class="text-link" href="{{ route('manage.index','roles') }}">Reset</a>@endif</form><div class="table-wrap"><table><thead><tr><th>Role</th><th>Team members</th><th>Access</th><th class="text-right">Actions</th></tr></thead><tbody>
@forelse($rows as $role)@php($admin=$role->system && $role->name==='Administrator') @php($canManage=auth()->user()->isAdministrator() || (\App\Support\SalesVisibility::canGrant($role->sales_visibility??'ALL',$role) && $role->permissions->whereIn('name',array_keys(\App\Support\Permissions::visible()))->every(fn($p)=>auth()->user()->hasPermission($p->name))))
<tr><td><div class="role-identity"><span class="role-avatar"><x-icon name="{{ $admin?'shield-check':'users' }}"/></span><div><a class="text-link" href="{{ route('manage.show',['roles',$role->id]) }}">{{ $role->name }}</a><small>{{ $admin?'Automatic full access':($role->system?'Built-in team role':'Custom team role') }}</small></div></div></td><td><strong>{{ $role->users_count }}</strong><small class="cell-note">Assigned accounts</small></td><td>@if($admin)<span class="badge green">All permissions</span><small class="cell-note">Includes new functions automatically</small>@else<strong>{{ $role->permissions->whereIn('name',array_keys(\App\Support\Permissions::visible()))->count() }}</strong> <span class="muted">permissions</span><small class="cell-note">{{ $role->permissions->whereIn('name',array_keys(\App\Support\Permissions::visible()))->map(fn($p)=>\App\Support\Permissions::info($p->name)['group'])->unique()->count() }} modules enabled</small><small class="cell-note role-sales-scope">{{ \App\Support\SalesVisibility::OPTIONS[$role->sales_visibility??'ALL'] }}</small>@endif</td><td><div class="row-actions"><a class="btn secondary small" href="{{ route('manage.show',['roles',$role->id]) }}"><x-icon name="eye" :size="16"/>View</a>@if(!$admin && $canManage)@can('roles.edit')<a class="btn secondary small" href="{{ route('manage.edit',['roles',$role->id]) }}"><x-icon name="pencil" :size="16"/>Edit</a>@endcan @unless($role->system)@can('roles.delete')<form action="{{ route('manage.destroy',['roles',$role->id]) }}" method="POST" data-confirm="Delete this role? Assigned roles cannot be deleted.">@csrf @method('DELETE')<button class="icon-button text-danger" aria-label="Delete {{ $role->name }}"><x-icon name="trash-2" :size="18"/></button></form>@endcan @endunless @endif</div></td></tr>
@empty<tr><td colspan="4" class="empty-cell">No matching roles. Try another search.</td></tr>@endforelse
</tbody></table></div><div class="customer-pagination">{{ $rows->links() }}</div></section>
@endsection
